fix(grid-container): margins are not counted in scrollHeight (FE-3061)
Sage/carbon pull request #3311
Opened 2020-10-20 13:15 UTC by grabkowski

### Proposed behaviour
Change margins to paddings in the `grid-container`

### Current behaviour
When the Grid is placed in an container, it's margins
are not counted into scrollHeight in Firefox and Safari browsers.

This issue could be encountered when Grid is placed
as content of the Accordion Component

### Checklist

- [x] Commits follow our style guide
~~- [ ] Screenshots are included in the PR if useful~~
~~- [ ] All themes are supported if required~~
- [x] Unit tests added or updated if required
~~- [ ] Cypress automation tests added or updated if required~~
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Additional context

### Testing instructions

2020-10-21 07:42 UTC, edleeks87 submitted a review, later dismissed

2020-10-21 08:39 UTC, ianforster-sage requested changes
This commit requires instructions in the commit message for using our codemod command line to remap `m, ml, mr` etc to `p, pl, pr` etc

2020-10-22 08:14 UTC, ianforster-sage approved these changes

2020-10-22 08:20 UTC, edleeks87 approved these changes

2020-10-27 09:58 UTC, Alec-Walker-Sage approved these changes
Tested in Firefox, Safari, Chrome and Edge. The margin around the grid component has been changed to padding. The grid now displays correctly inside other components such as accordion.

2020-10-27 10:29 UTC, merged

2020-10-27 10:31 UTC, carbonci commented
:tada: This PR is included in version 46.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/46.0.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v46.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: