ci: set success dependency for chromatic
Sage/carbon pull request #3335
Opened 2020-10-28 13:54 UTC by DlgSHi

### Proposed behaviour

Change the triggering for a `chromatic` builds from `pull_request` / `push` to a `repository_dispatch: types [chromatic_pr]`. This change will start `chromatic` build only when `cypress` one will be marked as `successfully`, and will help us to spend less unnecessary resources on `chromatic`.

### Current behaviour

To avoid losing of `chromatic` resources we need to:
- investigate the possibility to run chromatic build only after Cypress build will be finished with success;
- do a refactor for an existing yaml files.

### Checklist

- [x] Commits follow our style guide
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Carbon implementation and Design System documentation are congruent

2020-10-29 09:07 UTC, sjohnson-sage submitted a review, later dismissed

2020-10-29 10:58 UTC, sjohnson-sage approved these changes

2020-10-29 11:45 UTC, jamime requested changes

2020-10-29 11:45 UTC, jamime commented on .github/workflows/chromatic-push.yml
> -name: Chromatic Push
We need to keep this file to update the baselines after a PR is merged.
Please remove the `trigger-integration` branch we'll handle that in `cypress-push`

2020-10-29 11:45 UTC, jamime commented on .github/workflows/cypress-push.yml
> +      - trigger-integration # This branch is used to update checks on PR's from forks
Please revert branches, we'll handle them in `chrmatic-push`

2020-10-29 13:09 UTC, jamime approved these changes

2020-10-29 13:12 UTC, sjohnson-sage approved these changes

2020-10-29 13:12 UTC, merged

2020-10-30 08:46 UTC, carbonci commented
:tada: This PR is included in version 47.1.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/47.1.2)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v47.1.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: