fix(radio-button): warning when react node passed in label prop
Sage/carbon pull request #3346
Opened 2020-11-02 15:01 UTC by grabkowski

form field label accepts react node as a valid content,
user should have possibility to pass it down from the radio button

### Checklist

- [x] Commits follow our style guide
~~- [ ] Screenshots are included in the PR if useful~~
~~- [ ] All themes are supported if required~~
~~- [ ] Unit tests added or updated if required~~
~~- [ ] Cypress automation tests added or updated if required~~
~~- [ ] Storybook added or updated if required~~
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Additional context

### Testing instructions

2020-11-02 15:20 UTC, edleeks87 submitted a review, later dismissed

2020-11-02 17:17 UTC, jamime reviewed
Code looks fine, is there a way I can test this change. If this is related to FE-3182 I think we should add a MDX example, using the `Typography` component as the label.

2020-11-03 09:46 UTC, grabkowski commented
> Code looks fine, is there a way I can test this change. If this is related to FE-3182 I think we should add a MDX example, using the `Typography` component as the label.

I have added a story to the Textbox Component as we don't have the Label as a standalone component in our storybook.

2020-11-03 11:53 UTC, jamime requested changes

2020-11-03 11:53 UTC, jamime commented on src/__experimental__/components/radio-button/radio-button.stories.mdx
> +            Bold <Typography as='span'>regular</Typography> <Typography variant='em'>emphasized</Typography>
I don't think everything should be in the `b` tag.

```js
<><Typography variant='b'>Bold</Typography> <Typography as='span'>regular</Typography> <Typography variant='em'>emphasized</Typography></>
```

2020-11-03 11:53 UTC, jamime commented on src/__experimental__/components/radio-button/radio-button.stories.mdx
> +Validations can be added to the radio group as a string or boolean.
Looks like you forgot to update this description.

2020-11-03 14:12 UTC, edleeks87 approved these changes

2020-11-03 14:25 UTC, jamime approved these changes

2020-11-04 09:44 UTC, merged

2020-11-06 11:26 UTC, carbonci commented
:tada: This PR is included in version 48.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/48.4.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v48.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: