chore(message): remove classic theme support - FE-3115
Sage/carbon pull request #3382
Opened 2020-11-13 16:28 UTC by mkrds

BREAKING CHANGE: message component no longer supports classic theme

This PR removes classic theme support from `Message` component

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

2020-11-16 10:24 UTC, DipperTheDan approved these changes

2020-11-16 14:25 UTC, jamime requested changes
Please can you add details about this codemod in the commit so it is included in the release note.

https://github.com/Sage/carbon-codemod/tree/master/transforms/message-remove-classic-theme

2020-11-16 14:25 UTC, jamime commented on src/components/message/message.spec.js
> +          // theme={classicTheme}
Please remove commented code

2020-11-16 14:25 UTC, jamime commented on src/components/message/message.spec.js
> +          // theme={classicTheme}
Please remove commented code

2020-11-16 16:29 UTC, DipperTheDan approved these changes

2020-11-17 09:45 UTC, jamime approved these changes

2020-11-17 10:24 UTC, DipperTheDan approved these changes

2020-11-18 16:07 UTC, Alec-Walker-Sage approved these changes

2020-11-18 16:32 UTC, merged

2020-11-25 10:17 UTC, carbonci commented
:tada: This PR is included in version 50.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/50.0.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v50.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: