chore(settings-row): remove classic theme support - FE-3121
Sage/carbon pull request #3389
Opened 2020-11-16 15:05 UTC by mkrds

### Proposed behaviour
This PR removes classic theme support from `SettingsRow` component.
This PR also refactors all stories to CSF/MDX formats.

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

2020-11-16 16:03 UTC, DipperTheDan commented on src/components/settings-row/settings-row.component.js
> +SettingsRow.defaultProps = {
Could this be removed and the default be declared in the object on line 13? Something like:
`const { 
    title, 
    description, 
    children, 
    className, 
    divider = true 
  } = props;`

2020-11-16 16:03 UTC, DipperTheDan commented on src/components/settings-row/settings-row.style.js
> +  color: ${({ theme }) => theme.palette.slateTint(20)};
Nice little bit of tidying up 😉

2020-11-16 16:39 UTC, DipperTheDan submitted a review, later dismissed

2020-11-16 17:07 UTC, edleeks87 commented on src/components/settings-row/__snapshots__/settings-row.spec.js.snap
> +exports[`SettingsRow render renders properly 1`] = `
We need to avoid the theme object in snapshots as we'll need to update them each time the theme is modified

2020-11-16 17:10 UTC, edleeks87 requested changes
Please can you remove the theme object from the snapshot

2020-11-17 07:39 UTC, DlgSHi reviewed
We also need to modify the `accessibility` test for `Settings Row` component in `cypress/features/regression/accessibility/accessibilityCommon.feature` line 62

2020-11-18 11:27 UTC, DipperTheDan approved these changes

2020-11-18 17:39 UTC, edleeks87 approved these changes

2020-11-19 09:36 UTC, DipperTheDan approved these changes

2020-11-19 12:12 UTC, DlgSHi approved these changes

2020-11-19 13:02 UTC, merged

2020-11-25 10:17 UTC, carbonci commented
:tada: This PR is included in version 50.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/50.0.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v50.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: