docs(dev-environment-setup): add GPG signing instructions
Sage/carbon pull request #3390
Opened 2020-11-16 15:40 UTC by ianforster-sage

### Proposed behaviour
Adds instructions on enabling GPG signing of git commits.

### Current behaviour
This is not in our current documentation.

### Checklist

- [x] Commits follow our style guide
~- [ ] Screenshots are included in the PR if useful~
~- [ ] All themes are supported if required~
~- [ ] Unit tests added or updated if required~
~- [ ] Cypress automation tests added or updated if required~
~- [ ] Storybook added or updated if required~
- [ ] Typescript `d.ts` file added or updated if required
~- [ ] Carbon implementation and Design System documentation are congruent~

### Testing instructions
Read it and test the links.

2020-11-16 15:52 UTC, edleeks87 commented on docs/dev-environment-setup.md
> +We encourage our contributors to verify their commits with a GPG key. Follow these instruction enable GPG commit signing: [https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-git
```suggestion
We encourage our contributors to verify their commits with a GPG key. Follow these instructions to enable GPG commit signing: [https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/managing-commit-signature-verification](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/managing-commit-signature-verification)
```

2020-11-16 16:17 UTC, edleeks87 approved these changes

2020-11-16 16:25 UTC, jamime requested changes

2020-11-16 16:25 UTC, jamime commented on docs/dev-environment-setup.md
> +Then execute this command:
```suggestion
Then execute this command to sign all of your commits by default:
```

2020-11-16 16:25 UTC, jamime commented on docs/dev-environment-setup.md
> +Then add this to your profile:
```suggestion
Then add this to your profile (i.e`~/.zshrc` or `~/.bashrc`) so `gpg-agent` can prompt for your passphrase:
```

2020-11-16 16:25 UTC, jamime commented on docs/dev-environment-setup.md
> +`$ export GPG_TTY=$(tty)`
```suggestion
`export GPG_TTY=$(tty)`
```

2020-11-16 17:13 UTC, jamime approved these changes

2020-11-17 09:23 UTC, edleeks87 approved these changes

2020-11-17 12:11 UTC, DlgSHi approved these changes

2020-11-17 12:13 UTC, merged

2020-11-17 13:11 UTC, carbonci commented
:tada: This PR is included in version 49.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/49.0.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v49.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: