chore: remove classic theme FieldHelp and FormField - FE-3358/FE-3359
Sage/carbon pull request #3441
Opened 2020-11-26 17:22 UTC by mkrds

This PR removes classic theme styles from both FormField and FieldHelp components

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

2020-11-26 17:25 UTC, edleeks87 approved these changes

2020-11-27 11:11 UTC, dawidzarzycki requested changes

2020-11-27 11:11 UTC, dawidzarzycki commented on src/__experimental__/components/form-field/form-field.spec.js
>  import { shallow, mount } from "enzyme";
consol error in this test file 
![image](https://user-images.githubusercontent.com/19231884/100443171-79713280-30a9-11eb-8445-406f11a92713.png)

2020-11-27 12:21 UTC, dawidzarzycki approved these changes

2020-11-27 14:59 UTC, edleeks87 approved these changes

2020-12-01 09:01 UTC, Alec-Walker-Sage approved these changes

2020-12-01 10:23 UTC, merged

2020-12-09 12:10 UTC, carbonci commented
:tada: This PR is included in version 54.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/54.0.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v54.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: