chore(dialog-full-screen/full-screen-heading): remove classic theme - FE-3633/FE-3361
Sage/carbon pull request #3456
Opened 2020-12-01 13:56 UTC by DipperTheDan

removal of classic theme from dialog full screen and full screen heading components. These two
components have been done as a pair as dialog full screen uses full screen heading.

BREAKING CHANGE: removal of classic theme from dialog full screen component.

fixes FE-3633 and FE-3361

### Proposed behaviour

Removal of classic theme from dialog-full-screen and full-screen-heading.

### Current behaviour
Dialog-full-screen and full-screen-heading currently support classic theme.

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Additional context
N/A

### Testing instructions
- There should be no classic theme for dialog-full-screen and full-screen-heading.
- Build should pass.
- Cypress tests pass.

2020-12-02 16:02 UTC, edleeks87 requested changes
There's a few files that we should also update, I'll message you offline about them and see what you think

2020-12-02 16:30 UTC, edleeks87 approved these changes

2020-12-02 17:36 UTC, mkrds approved these changes

2020-12-03 08:56 UTC, DlgSHi approved these changes

2020-12-03 08:56 UTC, DlgSHi commented
approve for a changes in code - needs to be QA'd

2020-12-03 11:46 UTC, merged

2020-12-08 17:11 UTC, carbonci commented
:tada: This PR is included in version 53.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/53.0.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v53.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: