fix(menu): allow null children
Sage/carbon pull request #3499
Opened 2020-12-16 10:50 UTC by sjohnson-sage

### Proposed behaviour
Allow null children in `Menu`

### Current behaviour
When conditionally rendering children in the `Menu`, when the child is set to null it causes an error.

### Checklist

- [ ] Commits follow our style guide
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Carbon implementation and Design System documentation are congruent

### Additional context

### Testing instructions

2020-12-16 13:12 UTC, jamime requested changes
Please can you add a unit test.

2020-12-16 13:12 UTC, jamime commented on src/components/menu/__internal__/submenu/submenu.component.js
> +            React.Children.toArray(children)[nextIndex] &&
I think we should move `React.Children.toArray` to be on L134 and re-use the value.

2020-12-16 13:42 UTC, edleeks87 approved these changes

2020-12-16 18:06 UTC, jamime approved these changes

2020-12-17 10:09 UTC, edleeks87 approved these changes

2020-12-18 14:57 UTC, DlgSHi approved these changes

2020-12-18 14:58 UTC, merged

2020-12-18 15:01 UTC, carbonci commented
:tada: This PR is included in version 54.3.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/54.3.4)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v54.3.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: