docs(roadmap): add public development roadmap
Sage/carbon pull request #3624
Opened 2021-01-29 16:25 UTC by ianforster-sage

### Proposed behaviour
As a public open-source project that's now being used by developers outside of Sage, as well as more widely within the organisation we should be publishing a roadmap.

### Current behaviour
No public development roadmap exists for Carbon.

### Checklist

- [x] Commits follow our style guide
~- [ ] Screenshots are included in the PR if useful~
~- [ ] All themes are supported if required~
~- [ ] Unit tests added or updated if required~
~- [ ] Cypress automation tests added or updated if required~
~- [] Storybook added or updated if required~
~- [ ] Typescript `d.ts` file added or updated if required~
- [x] Carbon implementation and Design System documentation are congruent

### Testing instructions
View in Documentation/Development Roadmap

2021-01-29 16:30 UTC, sjohnson-sage commented on docs/development-roadmap.stories.mdx
> +1. Table Ajax
Should be `2.` and `3.` I think

2021-01-29 16:32 UTC, sjohnson-sage commented on docs/development-roadmap.stories.mdx
> +1. Keyboard accessibility of Tables - particularly tables with inputs.
Same comment as below

2021-02-01 17:18 UTC, jamime requested changes

2021-02-01 17:18 UTC, jamime commented on docs/development-roadmap.stories.mdx
> +Move the experimental components into the main components folder and remove the experimental folder
```suggestion
Move the experimental components into the main components folder and remove the experimental folder.
```

2021-02-01 17:18 UTC, jamime commented on docs/development-roadmap.stories.mdx
> +Implement the proposal in the [i18n RFC](https://github.com/Sage/carbon/blob/master/rfcs/text/i18n.md)
```suggestion
Implement the proposal in the [i18n RFC](https://github.com/Sage/carbon/blob/master/rfcs/text/i18n.md).
```

2021-02-01 17:18 UTC, jamime commented on docs/development-roadmap.stories.mdx
> + At a minimum we should support TypeScript by providing typings files for every component and enabling support in our build pipeline.
I don't think theres anything we need to do in the build pipeline, we already support `d.ts` files.
```suggestion
 At a minimum we should support type definitions for every component.
```

2021-02-01 17:18 UTC, jamime commented on docs/development-roadmap.stories.mdx
> +We will also review if we should migrate the Carbon repo to use TypeScript completely as there are many benefits to using TypeScript.
```suggestion
We will also review if we should convert our existing code to TypeScript.
```

2021-02-01 17:18 UTC, jamime commented on docs/development-roadmap.stories.mdx
> +Replace with a higher order component
I don't think we should be supporting this any more, it's a helper for ImmutableJS which we no longer use.

2021-02-01 17:18 UTC, jamime commented on docs/development-roadmap.stories.mdx
> +### Deprecate components
```suggestion
### Deprecations
```
Let's move the `shouldComponentUpdate` into this list.

2021-02-01 17:18 UTC, jamime commented on docs/development-roadmap.stories.mdx
> +Automation/Testing/Linting to ensure that Accessibility is part of the CI process so it can’t get forgotten about or worse without us knowing.
```suggestion
Review our automation/testing/linting to ensure that accessibility is part of the CI process to prevent any regressions.
```

2021-02-04 14:56 UTC, jamime approved these changes

2021-02-04 15:15 UTC, merged

2021-02-05 10:06 UTC, carbonci commented
:tada: This PR is included in version 63.4.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/63.4.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v63.4.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: