fix(card): add overflow: auto to card style (FE-3463)
Sage/carbon pull request #3682
Opened 2021-02-12 15:36 UTC by ianforster-sage

fixes: #3519

### Proposed behaviour
Adds overflow: auto to the Card style, this corrects the spacing seen at the bottom of the Card.
<img width="630" alt="Screenshot 2021-02-12 at 15 29 23" src="https://user-images.githubusercontent.com/35449967/107787688-591b5080-6d47-11eb-8a43-efbe58cf6dc3.png">

### Current behaviour
Described in the linked issue https://github.com/Sage/carbon/issues/3519

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
~- [ ] Cypress automation tests added or updated if required~
~- [ ] Storybook added or updated if required~
~- [ ] Typescript `d.ts` file added or updated if required~
- [x] Carbon implementation and Design System documentation are congruent

### Additional context
N/a

### Testing instructions
https://codesandbox.io/s/dazzling-sanderson-qpyq1

2021-02-12 15:47 UTC, DipperTheDan submitted a review, later dismissed

2021-02-12 17:04 UTC, bulaj submitted a review, later dismissed

2021-02-15 14:30 UTC, edleeks87 requested changes
I think we should replace the margin in `CardRow` with padding instead. We would need to add something to adjust the padding (top) when there is more than one `CardRow` to avoid the spacing in the pic below 

![image](https://user-images.githubusercontent.com/44157880/107958719-57959680-6f9a-11eb-856b-af6b61b32790.png)

2021-02-22 15:15 UTC, edleeks87 approved these changes

2021-02-22 15:16 UTC, bulaj approved these changes

2021-02-23 16:22 UTC, edleeks87 submitted a review, later dismissed

2021-02-23 16:23 UTC, bulaj approved these changes

2021-02-25 11:25 UTC, Alec-Walker-Sage reviewed
Could we also change the description for spacing in the CardFooter prop to be something similar to how it is in CardRow at the moment because I believe it works the same

2021-02-25 11:25 UTC, Alec-Walker-Sage commented on src/components/card/card-row/card-row.component.js
> +  /** Predefined size of card for applying padding (small | medium | large). For more granular control these can be over-ridden by Padding props from styled-system (see table below). */
Could we make it more clear that padding is set by the spacing prop on Card and setting a spacing prop in CardRow will do nothing. 
```suggestion
  /** Spacing prop is set in Card and defines the padding for the CardRow (the first CardRow has no padding by default) For more granular control of CardRow padding these can be over-ridden by Padding props from styled-system (see table below). */
```

2021-02-25 12:07 UTC, Alec-Walker-Sage approved these changes

2021-02-25 12:08 UTC, bulaj approved these changes

2021-02-25 12:33 UTC, edleeks87 approved these changes

2021-02-25 13:51 UTC, merged

2021-02-25 13:54 UTC, carbonci commented
:tada: This PR is included in version 66.14.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/66.14.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v66.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: