feat: add an option to make a link from Tab - FE-3486
Sage/carbon pull request #3685
Opened 2021-02-15 09:59 UTC by dawidzarzycki

### Proposed behaviour
![image](https://user-images.githubusercontent.com/19231884/107931511-a9c7bf00-6f7c-11eb-8ff9-4d3118c68618.png)

### Current behaviour
There is no possibility to make a link from Tab

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [ ] <del> All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [ ] <del> Carbon implementation and Design System documentation are congruent

### Additional context

### Testing instructions

2021-02-15 10:50 UTC, bulaj commented
![image](https://user-images.githubusercontent.com/5004407/107937172-db905400-6f83-11eb-8830-999dc3c7b1a2.png)
Isn't it a little misaligned vertically? macOs safair, on chrome looks the same

2021-02-15 12:24 UTC, bulaj requested changes

2021-02-15 12:24 UTC, bulaj commented on src/components/tabs/__internal__/tab-title/tab-title.component.js
> +          as={href && "a"}
Initialize ``const hasHref = !!href`` at the top to make it a litttle more verbose and avoid possible xss.

2021-02-15 16:14 UTC, edleeks87 commented on src/components/tabs/__internal__/tab/tab.d.ts
> +  href: string;
```suggestion
  href?: string;
```

2021-02-15 16:16 UTC, edleeks87 reviewed
Not much else to add past what @bulaj has raised already, happy to approve once they've been addressed

2021-02-15 16:26 UTC, edleeks87 commented
While you're updating this component @dawidzarzycki, could you move the `tab` directory, `tabs.component`, `tabs.d.ts`, `tabs.stories.js`, `tabs.spec.js`, `tabs.stories.mdx` and `tabs.style.js` out of the `__internal__` folder as well please? We've changed our planned approach since they were moved there originally.

2021-02-16 15:22 UTC, bulaj approved these changes

2021-02-16 15:24 UTC, bulaj approved these changes

2021-02-16 15:34 UTC, edleeks87 commented on src/components/tabs/tabs.d.ts
> +import Tab from '../tab';
```suggestion
import Tab from './tab';
```

2021-02-17 09:17 UTC, edleeks87 submitted a review, later dismissed

2021-02-17 10:00 UTC, bulaj submitted a review, later dismissed

2021-02-18 12:02 UTC, bulaj submitted a review, later dismissed

2021-02-18 13:34 UTC, DlgSHi commented on cypress/features/regression/test/tabs.feature
> +    Given I open "Design System Tabs" component page "with-link as a tab" in no iframe
```suggestion
    Given I open "Design System Tabs" component page "with link as a tab" in no iframe
```

2021-02-18 13:38 UTC, DlgSHi submitted a review, later dismissed

2021-02-18 14:57 UTC, edleeks87 approved these changes

2021-02-18 21:18 UTC, bulaj approved these changes

2021-02-19 06:46 UTC, DlgSHi approved these changes

2021-02-19 08:23 UTC, merged

2021-02-19 08:26 UTC, carbonci commented
:tada: This PR is included in version 66.10.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/66.10.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v66.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: