refactor(hr): update styled system implementation
Sage/carbon pull request #3885
Opened 2021-04-08 11:47 UTC by mmaciorowski-sage

BREAKING CHANGE: Use margin only. Padding has been removed.

### Proposed behaviour
`@styled-system/space` margin only (remove padding - breaking change).
Filter styled system margin props.

### Current behaviour
Uses no filtered `propTypes.space`.

### Checklist

- [x] Commits follow our style guide
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [ ] Carbon implementation and Design System documentation are congruent

### Additional context

### Testing instructions

2021-04-08 12:20 UTC, dawidzarzycki approved these changes

2021-04-08 12:33 UTC, dawidzarzycki commented on src/components/hr/hr.component.js
> +  ...marginPropTypes,
Is it not like we are changing from space into margins only in this case?

2021-04-08 12:35 UTC, dawidzarzycki requested changes
Left one comment, need confirmation

2021-04-08 12:46 UTC, dawidzarzycki commented on src/components/hr/hr.component.js
> +  ...marginPropTypes,
ignore this comment

2021-04-08 13:23 UTC, dawidzarzycki submitted a review, later dismissed

2021-04-08 15:04 UTC, edleeks87 approved these changes

2021-04-08 15:04 UTC, edleeks87 approved these changes

2021-04-09 11:53 UTC, dawidzarzycki submitted a review, later dismissed

2021-04-09 12:25 UTC, dawidzarzycki submitted a review, later dismissed

2021-04-09 14:11 UTC, edleeks87 approved these changes

2021-04-12 08:30 UTC, KatarzynaQA approved these changes

2021-04-13 09:08 UTC, edleeks87 approved these changes

2021-04-13 09:11 UTC, dawidzarzycki approved these changes

2021-04-13 09:15 UTC, KatarzynaQA approved these changes

2021-04-13 09:15 UTC, merged

2021-05-28 12:47 UTC, carbonci commented
:tada: This PR is included in version 76.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/76.0.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v76.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: