feat(text-editor): surface styled system margin props FE-3578
Sage/carbon pull request #3893
Opened 2021-04-09 14:42 UTC by edleeks87

### Proposed behaviour

Surfaces `styled-system/margin` props to allow adjusting of spacing for `TextEditor`

### Current behaviour

No margin props supported on `TextEditor`

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Additional context

### Testing instructions

will add sandbox

2021-04-09 14:46 UTC, dawidzarzycki requested changes
I think that you have to update text-editor.d.ts file as well

2021-04-09 14:47 UTC, dawidzarzycki approved these changes

2021-04-09 14:51 UTC, DipperTheDan approved these changes

2021-04-12 09:44 UTC, DlgSHi approved these changes

2021-04-12 09:50 UTC, DipperTheDan approved these changes

2021-04-12 09:51 UTC, merged

2021-04-12 09:53 UTC, carbonci commented
:tada: This PR is included in version 68.12.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/68.12.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v68.12.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: