fix(select): fix not resizing list during window resize - FE-3799
Sage/carbon pull request #3939
Opened 2021-04-21 17:25 UTC by mkrds

### Current behaviour
Select list is not resizing during window resize as shown in video in task description.

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Testing instructions

2021-04-21 21:50 UTC, bulaj submitted a review, later dismissed

2021-04-27 12:55 UTC, ianforster-sage requested changes
Please link to https://github.com/Sage/carbon/issues/3780 in your commit message

2021-04-28 09:10 UTC, edleeks87 approved these changes

2021-04-28 09:13 UTC, edleeks87 approved these changes

2021-04-28 12:37 UTC, DlgSHi submitted a review, later dismissed

2021-04-28 20:48 UTC, bulaj approved these changes

2021-04-29 05:59 UTC, DlgSHi approved these changes

2021-04-29 07:53 UTC, edleeks87 approved these changes

2021-04-29 08:09 UTC, ianforster-sage approved these changes

2021-04-29 08:15 UTC, merged

2021-04-29 08:17 UTC, carbonci commented
:tada: This PR is included in version 70.4.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/70.4.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v70.4.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: