feat(menu-item): add max width prop for truncation
Sage/carbon pull request #4008
Opened 2021-05-11 13:07 UTC by sjohnson-sage

### Proposed behaviour
Add a new `maxWidth` prop to `MenuItem`. If the title of the item exceeds the maximum width, it will automatically truncate.
This will also add a title attribute for hovering over the `MenuItem`.

![image](https://user-images.githubusercontent.com/14963680/117820134-24de0000-b262-11eb-88aa-b9432df8576e.png)

### Current behaviour
It is not currently possible to add truncation to `MenuItem` titles in this way.

### Checklist

- [ ] Commits follow our style guide
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Carbon implementation and Design System documentation are congruent

### Additional context

### Testing instructions
https://codesandbox.io/s/elastic-yonath-2lr7v?file=/src/index.js

2021-05-11 13:36 UTC, mmaciorowski-sage commented on src/components/menu/menu-item/menu-item.component.js
> +      title={maxWidth && typeof children === "string" ? children : ""}
maybe you should create a function?
some like:
`const getTitle = title => maxWidth && typeof title === "string" ? title : ""`

2021-05-11 13:45 UTC, edleeks87 submitted a review, later dismissed

2021-05-11 16:32 UTC, jamime commented on src/components/menu/__internal__/submenu/submenu.component.js
> +  /** Maximum width in px */
I think we could relax this to allow any CSS string.

2021-05-12 08:08 UTC, edleeks87 approved these changes

2021-05-12 08:14 UTC, mmaciorowski-sage approved these changes

2021-05-12 09:07 UTC, jamime commented on src/components/menu/__internal__/submenu/submenu.component.js
> +  maxWidth: PropTypes.number,
```suggestion
  maxWidth: PropTypes.string,
```

2021-05-12 09:08 UTC, jamime requested changes

2021-05-12 09:08 UTC, jamime commented on src/components/menu/__internal__/submenu/submenu.component.js
> +  /** Maximum width in px */
```suggestion
```

2021-05-12 09:11 UTC, sjohnson-sage commented on src/components/menu/__internal__/submenu/submenu.component.js
> +  /** Maximum width in px */
🤦🏻

2021-05-12 09:26 UTC, jamime approved these changes

2021-05-12 09:27 UTC, edleeks87 approved these changes

2021-05-12 09:28 UTC, mmaciorowski-sage approved these changes

2021-05-13 12:59 UTC, KatarzynaQA approved these changes

2021-05-13 13:27 UTC, merged

2021-05-13 13:29 UTC, carbonci commented
:tada: This PR is included in version 73.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/73.6.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v73.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: