fix(checkable-inputs): fix name prop forwarding - FE-3743
Sage/carbon pull request #4029
Opened 2021-05-17 12:56 UTC by mkrds

### Proposed behaviour
This PR adds `name` propType to Checkbox and Switch components

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Testing instructions

2021-05-17 13:05 UTC, grabkowski requested changes
I think that you'll need to also take care of this:
https://github.com/Sage/carbon/blob/master/src/__internal__/checkable-input/checkable-input.component.js#L45

2021-05-17 13:17 UTC, grabkowski approved these changes

2021-05-18 08:01 UTC, sjohnson-sage reviewed
You just need to link the Github issue to this then I'll approve 👍🏻

2021-05-18 09:40 UTC, sjohnson-sage approved these changes

2021-05-19 09:00 UTC, DlgSHi approved these changes

2021-05-19 14:29 UTC, merged

2021-05-19 14:31 UTC, carbonci commented
:tada: This PR is included in version 74.3.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/74.3.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v74.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: