Update textbox.d.ts
Sage/carbon pull request #4087
Opened 2021-05-26 22:19 UTC by gregor-gh

Adding missing labelAlign prop to Textbox d.ts file

2021-05-27 08:31 UTC, ianforster-sage requested changes
Hi @gregor-gh, thanks for submitting your first PR to the Carbon repository. I noticed one or two areas that don't follow our guides, please could you correct these before we review it fully.

- your Git commit message doesn't follow our standard https://github.com/Sage/carbon/blob/master/CONTRIBUTING.md#git-commit-messages
- your PR should remain in Draft mode until after it's been peer reviewed
- your PR description should follow our template https://github.com/Sage/carbon/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Thanks again for your contribution, I'll watch the PR and get it reviewed once you've updated it. You can find our contributing guide here https://github.com/Sage/carbon/blob/master/CONTRIBUTING.md

2021-05-27 17:54 UTC, gregor-gh commented
Thanks Ian, I think I've updated everything. Was just a quick change I made my side that I figured I'd raise a PR for, wasn't reading too closely.

2021-06-03 09:24 UTC, ianforster-sage requested changes
Hey @gregor-gh thanks for the update. Our pipeline makes GPG verification mandatory for all contributors. You can see how to configure that here https://github.com/Sage/carbon/blob/master/docs/dev-environment-setup.md#gpg-verification
Please could you sign your commit and resubmit it then I can run the checks

2021-06-06 13:38 UTC, gregor-gh commented
Hi Ian, I've amended the commit with a GPG key as requested.

2021-06-09 14:38 UTC, ianforster-sage approved these changes

2021-06-09 14:49 UTC, mmaciorowski-sage approved these changes

2021-06-09 14:51 UTC, sjohnson-sage requested changes
We should add this to the `propTypes` in `textbox.component.js` as well so they match up

2021-06-10 08:48 UTC, gregor-gh commented
I've updated textbox.component.js to include labelAlign, and I've also gone back and amended textbox.d.ts to use OptionsHelper.AlignBinaryTypes, rather than explicitly state "left" | "right". "Size" was already specifying small/med/large so I've pointed that at OptionsHelper.SizesRestricted while I was in there; it now matches its textbox.component.js counterpart.

2021-06-11 09:22 UTC, ianforster-sage requested changes

2021-06-11 09:22 UTC, ianforster-sage commented on src/__experimental__/components/textbox/textbox.d.ts
> +import * as OptionsHelper from "../../../utils/helpers/options-helper";
OptionsHelper is soon to be removed by this PR https://github.com/Sage/carbon/pull/4134
I recommend that we delay merging this PR until #4134 is merged, then we'll advise on next steps for you

2021-07-23 13:53 UTC, dawidzarzycki commented
Hey @gregor-gh 
OptionsHelper has been removed in carbon version 79.0.0
We are no longer supporting for OptionsHelper and all types we do, should come from their own files.
Also storybook doesn't work with objects well. We should change values that come from object OptionsHelper with real values.
In your example it will be 
changing this
```js
labelAlign: PropTypes.oneOf(OptionsHelper.alignBinary),
```
to this
```js
labelAlign: PropTypes.oneOf(["left", "right"])
```

Also your d.ts files should be updated with real values instead of these that come from OptionsHelper

This is a link to PR with OptionsHelper
https://github.com/Sage/carbon/releases/tag/v79.0.0

2021-07-29 13:41 UTC, dawidzarzycki commented
labelAlign has been added to the textbox.d.ts file 
https://github.com/Sage/carbon/blob/master/src/components/textbox/textbox.d.ts#L35

I think this PR is no longer valid

2021-07-29 14:17 UTC, closed without merging