feat(flat-table): add styled-system pl support - FE-4160
Sage/carbon pull request #4174
Opened 2021-06-18 10:05 UTC by DipperTheDan

pl prop is now available to use on a flat-table-cell component

fixes #4145

### Proposed behaviour

Allows `pl` prop to be used on a `flat-table-cell`

### Current behaviour

`pl` value is overwritten by a hard-coded `padding-left: 4px` value.

### Checklist

- [x] Commits follow our style guide
- [ ] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Additional context
N/A

### Testing instructions
codesandbox will be provided

2021-06-21 08:08 UTC, edleeks87 requested changes
This needs to be a `fix` commit please, the padding props are already surfaced as part of the `FlatTableCell` interface. You'll also probably have to make the same changes to support `pl` in the `FlatTableRowHeader` as well

2021-06-21 09:04 UTC, edleeks87 approved these changes

2021-06-21 09:12 UTC, nicktitchmarsh submitted a review, later dismissed

2021-06-21 09:26 UTC, edleeks87 approved these changes

2021-06-23 22:03 UTC, sianford approved these changes

2021-06-23 22:10 UTC, sianford commented
Tested in codesandbox and Chromatic published Storybook in Safari, Chrome, Firefox and Edge. Testing passed ✅

2021-06-24 08:25 UTC, nicktitchmarsh approved these changes

2021-06-24 08:26 UTC, edleeks87 approved these changes

2021-06-24 08:37 UTC, sianford approved these changes

2021-06-24 08:37 UTC, merged

2021-06-24 08:40 UTC, carbonci commented
:tada: This PR is included in version 77.2.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/77.2.2)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v77.2.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: