feat(tooltip-provider): add context and provider component FE-4074
Sage/carbon pull request #4305
Opened 2021-08-13 10:54 UTC by edleeks87

fixes #3864
### Proposed behaviour

- Adds new `TooltipContext` and `TooltipProvider` component. The intention is that this will help to
avoid prop chaining tooltip props from root to a component composed lower in the tree
- Adds support for overriding the `tooltipPosition` via context to `Icon `component. This will prevent prop chaining the
value down several levels to the `Icon`
- Adds `TooltipProvider` and surfaces `tooltipPosition` prop in `Textbox` and `Textarea`
- Adds examples of functionality to `Textbox` based components
- `RadioButton` `Checkbox` and `Switch` integrates `TooltipProvider` and surfaces `tooltipPosition` prop

### Current behaviour

No support fro overriding default tooltip position for icons rendered as part of inputs

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Additional context

Default position:
![image](https://user-images.githubusercontent.com/44157880/129346664-ff4e6762-defd-438e-8d97-a1c5c13ab15d.png)

Override:
![image](https://user-images.githubusercontent.com/44157880/129346712-fbea9919-4723-4b4a-9a71-e5e2ff01385e.png)

### Testing instructions

Will add sandbox

2021-08-16 07:35 UTC, DipperTheDan commented on src/components/switch/switch.stories.mdx
> +<Preview>
Looks like when the tooltip of this example is hovered over the example applies hover state styling too. 
Might be an idea to check the other `group` components just to see if this happens too.

<img width="1385" alt="Screenshot 2021-08-16 at 08 34 22" src="https://user-images.githubusercontent.com/56251247/129527560-402a5953-f0de-4786-aa83-1374728bfd00.png">

2021-08-16 11:24 UTC, dawidzarzycki approved these changes

2021-08-16 12:48 UTC, DipperTheDan submitted a review, later dismissed

2021-08-16 13:54 UTC, DipperTheDan submitted a review, later dismissed

2021-08-16 13:56 UTC, dawidzarzycki approved these changes

2021-08-16 14:43 UTC, grabkowski requested changes

2021-08-16 14:43 UTC, grabkowski commented on src/__internal__/tooltip-provider/index.d.ts
> +export default TooltipProvider;
missing `TooltipContext` export

2021-08-16 15:01 UTC, grabkowski approved these changes

2021-08-16 15:05 UTC, dawidzarzycki approved these changes

2021-08-16 15:12 UTC, DipperTheDan approved these changes

2021-08-23 10:12 UTC, ZhuoyuJin approved these changes

2021-08-23 10:50 UTC, merged

2021-08-23 10:51 UTC, carbonci commented
:tada: This PR is included in version 81.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/81.3.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v81.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: