fix: added missing null check to element resize
Sage/carbon pull request #4323
Opened 2021-08-23 11:58 UTC by blaky

The form component uses a throttle function that calls triggers a call to ElementResize's `removeListener` function. By the time that the function is executed, the element might be removed from the DOM which results an unhandled error.

2021-08-23 16:17 UTC, jamime requested changes
Hi @blaky,

We have a detailed [pull request template](https://raw.githubusercontent.com/Sage/carbon/f23993ab5c939abcecbe4065409217f50a4eead5/.github/PULL_REQUEST_TEMPLATE.md) that would help us get this change approved faster.
In particular for QA we need a reproducible example in form of a codesandbox that shows the broken behaviour.

Our CI process then builds a new version and QA can then confirm that the bug is indeed fixed.

Please use the template to ensure the CI process picks up your codesandbox.

It would be good to update this test and find why it's not failing.
https://github.com/Sage/carbon/blob/0f4583451da684c575bc468b63db32730982faab/src/components/form/form.spec.js#L46-L62

We also require signed commits, there are instructions on how to do that [here](https://github.com/Sage/carbon/blob/ff9ce77d40bca4339f8b5a4bbd1eef65ef6c1d92/docs/dev-environment-setup.md#gpg-verification).

Thanks,
Jamie

2021-08-24 05:43 UTC, blaky commented
Hi @jamime ,

I tried to reproduce the issue in code sandbox but I couldn't isolate the problem from our project to here. It is very obvious that the null check is missing from this function, it is there for the addListener. Logically, this change cannot have any side-effects: so far if the value was not provided an exception was thrown which then was not handled, and forwarded to the consumer.

Kind regards,
Bence

2021-08-24 06:45 UTC, blaky commented
> Hi @blaky,
> 
> We have a detailed [pull request template](https://raw.githubusercontent.com/Sage/carbon/f23993ab5c939abcecbe4065409217f50a4eead5/.github/PULL_REQUEST_TEMPLATE.md) that would help us get this change approved faster.
> In particular for QA we need a reproducible example in form of a codesandbox that shows the broken behaviour.
> 
> Our CI process then builds a new version and QA can then confirm that the bug is indeed fixed.
> 
> Please use the template to ensure the CI process picks up your codesandbox.
> 
> It would be good to update this test and find why it's not failing.
> https://github.com/Sage/carbon/blob/0f4583451da684c575bc468b63db32730982faab/src/components/form/form.spec.js#L46-L62
> 
> We also require signed commits, there are instructions on how to do that [here](https://github.com/Sage/carbon/blob/ff9ce77d40bca4339f8b5a4bbd1eef65ef6c1d92/docs/dev-environment-setup.md#gpg-verification).
> 
> Thanks,
> Jamie

The test in question is not failing because it is doing one operation at the time. The `checkStickyFooter` function is throttled, which means that the first call is still fine, it can remove the listener form the DOM element while it is mounted, but subsequent calls to the function might get executed when the element is already destroyed. 
I am more than happy to show you our setup, we are also experiencing issues in the Form component's `getBoundingClientRect()` calls, but those don't end up blocking the user.

Thanks in advance,
Bence

2021-08-24 10:08 UTC, mkrds approved these changes

2021-08-24 11:05 UTC, jamime commented
@blaky thanks for updating the PR. We did some manual testing and found some scenarios that were not covered by this PR. We'd like to spend a bit more time and deliver a more robust solution for you. 

We have the ticket FE-4290 which is in progress now.

In particular, we're going to remove the `ResizeObserver` and replace it with our hook [`useResizeObserver`](https://github.com/Sage/carbon/blob/master/src/hooks/__internal__/useResizeObserver/index.js). In form we also found that it's possible to remove the event listener from the wrong element because it's not memoized correctly.
https://github.com/Sage/carbon/blob/0f4583451da684c575bc468b63db32730982faab/src/components/form/form.component.js#L73

We'll update this ticket once we've produced a fix.

2021-09-02 09:14 UTC, closed without merging