fix(select-list): add a prevent default function when the enter key is pressed - FE-4206
Sage/carbon pull request #4328
Opened 2021-08-24 10:19 UTC by mmaciorowski-sage

### Proposed behaviour
Add a prevent default function when the enter key is pressed

### Current behaviour
https://github.com/Sage/carbon/issues/4216

### Checklist

- [x] Commits follow our style guide
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Carbon implementation and Design System documentation are congruent

### Additional context
Resolves: #4216 

### Testing instructions

2021-08-24 10:33 UTC, grabkowski requested changes
I think that you should change the message to be more descriptive for users, e.g.:

`fix(select): stop form submit when enter key is pressed with open list`

2021-08-24 14:55 UTC, sjohnson-sage approved these changes

2021-08-25 08:57 UTC, grabkowski approved these changes

2021-08-30 08:47 UTC, ZhuoyuJin approved these changes

2021-08-30 09:07 UTC, merged

2021-08-30 09:10 UTC, carbonci commented
:tada: This PR is included in version 83.0.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/83.0.2)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v83.0.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: