refactor(icon): use design tokens to describe icon component
Sage/carbon pull request #4520
Opened 2021-10-28 05:11 UTC by mjaniczko-sage

### Proposed behaviour
Describes the icon using design tokens. Removes all possible 'theme' in css files (left theme where calling styledColor function).

### Current behaviour
Icon styles use design tokens

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

2021-11-04 08:27 UTC, jhajduk-sage submitted a review, later dismissed

2021-11-23 15:51 UTC, samtjo requested changes

2021-11-23 15:51 UTC, samtjo commented on src/components/icon/icon.style.js
>          const { color: renderedColor } = styledColor({ color, theme });
We're still using theme on this line and in multiple other places in this component, they should be changed to use tokens in this PR I believe

2021-11-23 15:57 UTC, samtjo requested changes
I think you've missed the `theme.colors.focus` here: https://github.com/Sage/carbon/blob/e720ba81cdaec5866878a1a3fedea9412557f510/src/components/icon/icon.style.js#L136

2021-11-30 08:39 UTC, jhajduk-sage approved these changes

2021-11-30 10:38 UTC, samtjo submitted a review, later dismissed

2021-11-30 11:48 UTC, DipperTheDan submitted a review, later dismissed

2021-12-13 14:59 UTC, samtjo submitted a review, later dismissed

2021-12-14 11:23 UTC, DipperTheDan approved these changes

2021-12-21 10:05 UTC, DlgSHi submitted a review, later dismissed

2022-01-11 11:35 UTC, samtjo approved these changes

2022-01-11 11:39 UTC, DipperTheDan submitted a review, later dismissed

2022-01-12 07:05 UTC, DlgSHi approved these changes

2022-01-12 09:18 UTC, DipperTheDan approved these changes

2022-01-12 09:24 UTC, merged

2022-01-12 09:26 UTC, carbonci commented
:tada: This PR is included in version 102.9.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/102.9.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v102.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: