feat(button): describe button component using design tokens
Sage/carbon pull request #4533
Opened 2021-11-04 12:26 UTC by JoannaMikul

### Proposed behaviour

Describes the button component using design tokens.
Changes the button background color for the `tertiary` type for the hover state.
Changes the border color and button color for the `dashed` type.
Changes the colors according to the DS design.
Adds missing props in the `button.style.js` file.
Updates tests after making the above changes.

### Current behaviour

The button component uses the theme styled-component property.
Currently for the `tertiary` type button in hover state the background does not change.
Currently for the `dashed` button type the color is (0, 0, 0, 0.65), border: rgb(153, 173, 182)
The propTypes in the css files are missing the props used.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

Button type - tertiary:
![teritaryButton](https://user-images.githubusercontent.com/44143630/140312384-8721e672-416a-4d8f-8a0a-54d1e60ee80d.PNG)

Button type - dashed:
![dashedButton](https://user-images.githubusercontent.com/44143630/140312459-9686e213-ba3e-4f73-afe2-4d081bb890ad.PNG)

### Testing instructions

The correct appearance can be checked in the component: Button.
For theme: mint and aegean there should be no differences.
Use devtools to check if buttons use css variables.

2021-11-04 12:51 UTC, jhajduk-sage approved these changes

2021-11-04 15:37 UTC, jhajduk-sage submitted a review, later dismissed

2021-11-24 16:01 UTC, samtjo approved these changes

2021-11-24 16:11 UTC, samtjo requested changes
Code all looks good, just realised it should be a `refactor` commit rather than a `feat`.

Edit - Ignore this, saying as we're updating colours etc as per the design system I think `feat` is fine!

2021-11-24 16:13 UTC, samtjo approved these changes

2021-11-30 16:39 UTC, mkrds approved these changes

2021-12-07 09:12 UTC, jhajduk-sage approved these changes

2021-12-13 14:29 UTC, mkrds approved these changes

2021-12-13 15:05 UTC, samtjo approved these changes

2021-12-13 15:05 UTC, samtjo submitted a review, later dismissed

2021-12-15 16:05 UTC, samtjo approved these changes

2021-12-16 09:00 UTC, mkrds approved these changes

2021-12-20 09:27 UTC, DlgSHi approved these changes

2021-12-20 09:29 UTC, DlgSHi commented
There is an issue with Chromatic whereby it is not changing the theme to aegean or generic (none) to snapshot for those components that have Chromatic tests. Although this is not affecting Loader, the fix needs to be applied to the PR. Awaiting an update with the fix before this can be retested and merged.

2022-01-05 08:22 UTC, merged

2022-01-05 08:23 UTC, carbonci commented
:tada: This PR is included in version 102.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/102.5.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v102.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: