feat(link): describe link component using design tokens
Sage/carbon pull request #4565
Opened 2021-11-17 07:51 UTC by mjaniczko-sage

### Proposed behaviour

### Current behaviour

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

2021-11-24 16:11 UTC, samtjo requested changes
Code all looks good, it should be a `refactor` commit rather than a `feat` though

2021-11-25 11:42 UTC, samtjo approved these changes

2021-11-30 08:44 UTC, jhajduk-sage submitted a review, later dismissed

2021-11-30 10:41 UTC, samtjo submitted a review, later dismissed

2021-11-30 11:23 UTC, DipperTheDan approved these changes

2021-11-30 11:24 UTC, DipperTheDan approved these changes

2021-12-13 13:09 UTC, samtjo submitted a review, later dismissed

2021-12-13 16:10 UTC, ZhuoyuJin approved these changes

2021-12-14 10:04 UTC, DipperTheDan approved these changes

2021-12-14 11:11 UTC, DipperTheDan approved these changes

2021-12-14 11:15 UTC, samtjo approved these changes

2021-12-14 11:17 UTC, ZhuoyuJin approved these changes

2021-12-14 11:17 UTC, merged

2021-12-14 11:20 UTC, carbonci commented
:tada: This PR is included in version 102.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/102.3.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v102.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: