style(button): darken mint's primary colour to comply with WCAG (FE-4474)
Sage/carbon pull request #4597
Opened 2021-11-29 11:44 UTC by Parsium

### Proposed behaviour

Change degree of shading in `mint` theme, to bring the contrast ratio between the background color of `Dialog` and the text color of secondary/tertiary `Button` to 4.82:1

### Current behaviour

Contrast ratio between `Dialog` background and secondary/tertiary `Button` text is 4.48:1, which falls below the minimum ratio outlined in the WCAG 2.1 guidelines of 4.5:1

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

To verify contrast ratio, and that no other accessibility violations are being raised.

2021-11-29 11:53 UTC, grabkowski approved these changes

2021-11-29 11:56 UTC, samtjo requested changes
This change should be for the tertiary button only, not the whole theme 👍🏻

2021-11-30 13:15 UTC, grabkowski approved these changes

2021-11-30 16:01 UTC, samtjo submitted a review, later dismissed

2021-12-01 14:17 UTC, DipperTheDan approved these changes

2021-12-01 14:18 UTC, DipperTheDan submitted a review, later dismissed

2021-12-02 07:48 UTC, grabkowski approved these changes

2022-01-05 13:38 UTC, closed without merging