refactor(detail): refactor Detail component to use cypress-react - FE-4533
Sage/carbon pull request #4682
Opened 2022-01-06 23:45 UTC by sianford

### Proposed behaviour

Refactor for `Detail` component to use new `cypress-component-react` framework for testing.

### Current behaviour

Currently we are using the regular `cypress` approach with BDD.

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

 - [ ] Run npx cypress open-ct to check if there is newly added test.file
 - [ ] Check if the grouped-character.test.js file passed
 - [ ] Compare all tests were moved/refactored from .feature file -> .test.js file
 - [ ] Check if all unnecessary files were deleted

2022-01-07 13:09 UTC, DipperTheDan submitted a review, later dismissed

2022-01-10 16:46 UTC, Parsium submitted a review, later dismissed

2022-01-10 17:18 UTC, ZhuoyuJin submitted a review, later dismissed

2022-01-11 09:11 UTC, DlgSHi requested changes
We need to delete also one more file `./cypress/fixtures/commonComponents/detail.json`

2022-01-11 09:11 UTC, DlgSHi commented on src/components/detail/detail.test.js
> +        // and mount the story using @cypress/react library
we can remove those comments in TC.

2022-01-11 16:43 UTC, Parsium approved these changes

2022-01-11 16:49 UTC, DipperTheDan approved these changes

2022-01-11 17:16 UTC, ZhuoyuJin approved these changes

2022-01-12 10:13 UTC, DlgSHi approved these changes

2022-01-12 11:13 UTC, merged

2022-01-13 11:19 UTC, carbonci commented
:tada: This PR is included in version 102.9.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/102.9.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v102.9.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: