fix(navigation-bar): add z-index so NavigationBar stacks just below Modals
Sage/carbon pull request #4733
Opened 2022-01-20 10:35 UTC by edleeks87

fix #4690

### Proposed behaviour

Sets the z-index of NavigationBar to stack it just below Modals and displays over main UI components

![image](https://user-images.githubusercontent.com/44157880/150321765-ec9e09e2-c8a9-43a7-bbde-d91d41e9defe.png)

### Current behaviour

Has no z-index so does not stack over main UI components

![image](https://user-images.githubusercontent.com/44157880/150321889-97232664-f337-429c-9b22-321ed2a70779.png)

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] Unit tests added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

2022-01-20 12:15 UTC, mkrds commented on src/components/navigation-bar/navigation-bar.style.js
> +    z-index: ${String(theme.zIndex.modal - 1)};
This actually should be a number I think

2022-01-21 12:26 UTC, grabkowski approved these changes

2022-01-24 10:16 UTC, samtjo requested changes

2022-01-24 10:16 UTC, samtjo commented on src/components/navigation-bar/navigation-bar.style.ts
> +    z-index: ${theme.zIndex.modal - 1};
Let's create a `theme.zIndex.nav` variable for this, so we can work towards setting all the z indexes in one place

2022-01-24 10:52 UTC, samtjo approved these changes

2022-01-24 10:52 UTC, grabkowski approved these changes

2022-01-24 10:53 UTC, samtjo submitted a review, later dismissed

2022-01-31 16:32 UTC, divyajindel approved these changes

2022-02-08 09:43 UTC, divyajindel approved these changes

2022-02-08 09:45 UTC, grabkowski approved these changes

2022-02-08 09:51 UTC, samtjo approved these changes

2022-02-08 10:01 UTC, merged