refactor: deprecate AppWrapper (FE-3649)
Sage/carbon pull request #4757
Opened 2022-01-27 09:54 UTC by Parsium

BREAKING CHANGE

### Proposed behaviour

Deprecate `AppWrapper` - remove any remaining references to it in other components and storybook docs. Add deprecation warning to its code and own stories - replace use of `AppWrapper` with `Box` in these stories.

Also fix spelling mistake in `Row`'s deprecation warning.

### Current behaviour

`AppWrapper` has no deprecation warning in its code, and is used in a couple of stories.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

Check for any major regressions in the stories which used `AppWrapper` and will now use `Box`.

2022-01-27 10:28 UTC, samtjo requested changes
Hi @Parsium - this isn't actually a breaking change as you're just adding the deprecation warning, not deprecating the component. 

So this PR needs to change descriptions etc to be "Add deprecation warning to AppWrapper", or you need to actually remove the component if that's what's intended here 👍🏻

2022-01-27 10:28 UTC, samtjo commented on src/components/form/form.stories.mdx
> +            <Box p={"0px 40px"}>
```suggestion
            <Box p="0px 40px">
```

2022-01-27 10:28 UTC, samtjo commented on src/components/dialog-full-screen/dialog-full-screen.stories.mdx
> +            <Box p={"0px 40px"}>
```suggestion
            <Box p="0px 40px">
```

2022-01-27 10:28 UTC, samtjo commented on src/components/app-wrapper/app-wrapper.stories.mdx
> +  AppWrapper is now deprecated. Please use the{" "}
```suggestion
  AppWrapper is now deprecated. Please use the
```

2022-01-27 10:28 UTC, samtjo commented on src/components/app-wrapper/app-wrapper.stories.mdx
> +  </LinkTo>{" "}
```suggestion
  </LinkTo>
```

2022-01-27 10:35 UTC, DipperTheDan commented on src/components/row/row.stories.mdx
> +  Row and Column are both now deprecated. Please use the{" "}
I probably would leave this as is because Kuba is working on the deprecation of Row and Column.

2022-01-27 10:36 UTC, DipperTheDan commented on src/components/row/row.stories.mdx
> +  Row and Column are both now deprecated. Please use the{" "}
I probably would leave this as it was. Kuba is currently working on the deprecation of Row and Column.

2022-01-27 11:39 UTC, samtjo submitted a review, later dismissed

2022-01-27 11:48 UTC, DipperTheDan submitted a review, later dismissed

2022-01-31 10:24 UTC, samtjo submitted a review, later dismissed

2022-01-31 10:32 UTC, DipperTheDan approved these changes

2022-01-31 11:27 UTC, DlgSHi approved these changes

2022-02-08 10:33 UTC, samtjo approved these changes

2022-02-08 10:38 UTC, DipperTheDan approved these changes

2022-02-08 10:45 UTC, DlgSHi approved these changes

2022-02-08 10:45 UTC, merged

2022-02-08 13:32 UTC, carbonci commented
:tada: This PR is included in version 104.7.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/104.7.3)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v104.7.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: