feat(menu): describe menu using design tokens, update tests - FE-4724
Sage/carbon pull request #4764
Opened 2022-01-28 15:21 UTC by JoannaMikul

### Proposed behaviour

Describes menu component using the tokens of the design.
Describes focus state using tokens : `box-shadow: 0 0 0 var(--borderWidth300) var(--colorsSemanticFocus500)`.
Changes colors of the title segment: 
 - white: `var(--colorsComponentsMenuYin065)`
 - black: `var(--colorsComponentsMenuYang080)`
 - light: `var(--colorsComponentsMenuYin065)`
 - dark: `var(--colorsComponentsMenuYang080)`
 
 Changes the color for icon in search input: 
 - default: `var(--colorsUtilityMajor200)`
 - hover: `var(--colorsUtilityMajor150)`

### Current behaviour

Menu component use the theme styled-component property.
Current focus state is describe by box-shadow: `rgb(255 181 0) 0px 0px 0px 2px inset`.

Current colors of the title segment: 
 - white: `rgb(64, 102, 119)`
 - black: `rgb(153, 173, 182)`
 - light: `rgb(64, 102, 119)`
 - dark: `rgb(153, 173, 182)`
 
Current color for icon in search input: 
 - default: `rgb(140, 163, 173)`
 - hover: `rgb(191, 204, 210)`

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context
![image](https://user-images.githubusercontent.com/44143630/151572620-45ee5754-24dc-459c-b71b-fe43209911fd.png)
![image](https://user-images.githubusercontent.com/44143630/151572672-9c114baf-8825-4bfa-a218-29b631e664f7.png)
![image](https://user-images.githubusercontent.com/44143630/151572734-d6f3b5ca-0de5-44b5-984e-93d7b2de4606.png)
![image](https://user-images.githubusercontent.com/44143630/151572806-a3cb5897-45db-4360-9259-7e0e2a8d71b1.png)

### Testing instructions

The correct appearance can be checked in the component: Menu.
Use devtools to check if menu component use css variables.

2022-01-31 08:20 UTC, jhajduk-sage submitted a review, later dismissed

2022-01-31 11:06 UTC, Parsium commented on src/components/menu/__internal__/submenu/submenu.style.js
> +      button:hover {
It might be worth adding a small test for checking these stylings 👍🏼

2022-01-31 11:18 UTC, Parsium commented on src/components/menu/menu-full-screen/menu-full-screen.spec.js
>          assertStyleMatch(
This is assertion is a duplicate of the one on line 73 - can remove this?

2022-01-31 11:19 UTC, Parsium commented on src/components/menu/menu-full-screen/menu-full-screen.spec.js
> +            backgroundColor: menuConfigVariants[menuType].background,
This is assertion is a duplicate of the one on line 73 - can remove this?

2022-01-31 11:19 UTC, DipperTheDan reviewed
I agree with @Parsium. Once you've got those added everything looks good 👍🏻

2022-01-31 11:20 UTC, Parsium commented on src/components/menu/menu-full-screen/menu-full-screen.spec.js
>          assertStyleMatch(
This is assertion is a duplicate of the one on line 73 - can remove this?

2022-01-31 11:32 UTC, Parsium commented on src/components/menu/menu-full-screen/menu-full-screen.spec.js
>          assertStyleMatch(
It may be helpful to reorganise the assertions in this file into separate tests under a `describe.each()` for readability

2022-01-31 13:34 UTC, Parsium commented on src/components/menu/menu-item/menu-item.style.js
> +      }
Similarly to `Submenu`, I would add some additional tests to verify the token colours are being rendered correctly (in addition to the existing ones for the background colour).

2022-01-31 13:42 UTC, Parsium requested changes
Just needs those additional tests adding, but looks great 👍🏼

2022-02-01 15:25 UTC, Parsium reviewed
Looks great @JoannaMikul 👍🏼  Try squashing and rebasing the PR now to see if fixes for the failing `Date` tests have been made already and I'll approve ✅

2022-02-07 15:06 UTC, Parsium approved these changes

2022-02-07 15:15 UTC, DipperTheDan submitted a review, later dismissed

2022-02-08 10:42 UTC, DipperTheDan approved these changes

2022-02-08 11:44 UTC, Parsium approved these changes

2022-02-09 09:10 UTC, Parsium approved these changes

2022-02-09 09:33 UTC, DipperTheDan approved these changes

2022-02-11 10:37 UTC, Parsium submitted a review, later dismissed

2022-02-14 09:32 UTC, DipperTheDan approved these changes

2022-02-17 11:51 UTC, DipperTheDan approved these changes

2022-02-17 13:40 UTC, Parsium submitted a review, later dismissed

2022-02-18 15:09 UTC, Parsium approved these changes

2022-02-18 15:40 UTC, DipperTheDan approved these changes

2022-02-21 12:56 UTC, DlgSHi submitted a review, later dismissed

2022-02-21 13:09 UTC, Parsium approved these changes

2022-02-21 13:14 UTC, samtjo requested changes
Just blocking merge for now as I've found a bug with the styling here:

2022-02-22 08:11 UTC, DlgSHi approved these changes

2022-02-22 09:30 UTC, samtjo approved these changes

2022-02-22 09:31 UTC, merged

2022-02-22 09:34 UTC, carbonci commented
:tada: This PR is included in version 104.23.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/104.23.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v104.23.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: