feat(portrait, profile): describe portrait and profile using design tokens, update tests
Sage/carbon pull request #4775
Opened 2022-02-01 13:37 UTC by JoannaMikul

### Proposed behaviour

Describes profile and portrait components using design tokens.
Removes unused `theme` props.
Fixes icon rendering size.
In `Profiles` describes the size of the `name` and `email` using tokens.

### Current behaviour

Portrait and Profile components use the theme styled-component property.
Theme is now passed as props.
Icons have a fixed size regardless of the portrait size.
Name and email in the Profile is represented by px.

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

Portrait:
![image](https://user-images.githubusercontent.com/44143630/151977717-4f67981f-3d68-48b7-b397-50ccb44e19da.png)
![image](https://user-images.githubusercontent.com/44143630/151977778-75b5989f-4bda-4893-b67d-51f727b0fda0.png)
Profile:
![image](https://user-images.githubusercontent.com/44143630/151977947-8b4966e5-fdb6-4241-9409-49be9465d938.png)

### Testing instructions

The correct appearance can be checked in the components: Portrait and Profile.
For theme: mint and aegean there should be no differences.
Use devtools to check if components use css variables.

2022-02-03 10:31 UTC, jhajduk-sage approved these changes

2022-02-07 13:48 UTC, Parsium requested changes

2022-02-07 13:48 UTC, Parsium commented on src/components/profile/profile.stories.mdx
> +- Combines the [Portrait](/components/portrait) component in a single configuration.
This bullet point can be removed, as it's a bit confusing what this means.

2022-02-07 14:47 UTC, DipperTheDan reviewed
Everything looks good. Just address the changes requested by @Parsium and then I'll approve 👍🏻

2022-02-07 15:13 UTC, Parsium submitted a review, later dismissed

2022-02-07 15:13 UTC, DipperTheDan submitted a review, later dismissed

2022-02-08 10:42 UTC, DipperTheDan approved these changes

2022-02-08 11:42 UTC, Parsium submitted a review, later dismissed

2022-02-15 20:44 UTC, divyajindel submitted a review, later dismissed

2022-02-16 10:26 UTC, DipperTheDan approved these changes

2022-02-16 11:03 UTC, DipperTheDan approved these changes

2022-02-16 12:57 UTC, divyajindel approved these changes

2022-02-16 13:19 UTC, merged

2022-02-16 13:22 UTC, carbonci commented
:tada: This PR is included in version 104.18.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/104.18.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v104.18.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: