test(batch selection): add refactored tests for batch selection FE-4518
Sage/carbon pull request #4782
Opened 2022-02-03 12:01 UTC by divyajindel

### Proposed behaviour
Refactor for Batch Selection component to use new cypress-component-react framework for testing.
I have added test.js and deleted steps.js, feature and json files.

### Current behaviour

Currently we are using the regular cypress approach with BDD.

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ]  Run npx cypress open-ct to check if there is newly added test.file
- [ ]  Check if the batch-selection.test.js file passed
- [ ]  Compare all tests were moved/refactored from .feature file -> .test.js file
- [ ] Check if all unnecessary files were deleted, including .json file

2022-02-03 12:52 UTC, DlgSHi requested changes

2022-02-03 12:52 UTC, DlgSHi commented on src/components/batch-selection/batch-selection.test.js
> +          .focus();
I can't see any assertion here :(

2022-02-03 12:52 UTC, DlgSHi commented on src/components/batch-selection/batch-selection.test.js
> +  describe("check BatchSelection component count", () => {
in this `describe` we are checking the work of all component instead of `counter` only

2022-02-03 12:52 UTC, DlgSHi commented on src/components/batch-selection/batch-selection.test.js
> +    it("should check hidden batch selection", () => {
```suggestion
    it("should check hidden BatchSelection", () => {
```

2022-02-03 12:52 UTC, DlgSHi commented on src/components/batch-selection/batch-selection.test.js
> +    it("should check disabled batch selection", () => {
```suggestion
    it("should check disabled BatchSelection", () => {
```

2022-02-03 12:52 UTC, DlgSHi commented on src/components/batch-selection/batch-selection.test.js
> +  describe("check BatchSelection button position", () => {
this test is about being able to focus those buttons inside the `BatchSelection`

2022-02-03 13:09 UTC, DlgSHi requested changes

2022-02-03 13:09 UTC, DlgSHi commented on src/components/batch-selection/batch-selection.test.js
> +      ["white", "rgba(0, 0, 0, 0)"],
we have 4 themes here :)

2022-02-03 13:09 UTC, DlgSHi commented on src/components/batch-selection/batch-selection.test.js
> +            <IconButton onAction={() => {}}>
I'm not sure that we need `onAction={() => {}}`

2022-02-04 13:36 UTC, DlgSHi commented on src/components/batch-selection/batch-selection.test.js
> +  describe("check BatchSelection button position", () => {
the same question :)

2022-02-04 13:36 UTC, DlgSHi commented on src/components/batch-selection/batch-selection.test.js
> +            <IconButton onAction={() => {}}>
and this

2022-02-04 14:48 UTC, DlgSHi approved these changes

2022-02-04 16:06 UTC, DipperTheDan approved these changes

2022-02-09 06:35 UTC, DlgSHi reviewed
LGTM, just squash the commits, please

2022-02-09 16:44 UTC, DlgSHi approved these changes

2022-02-09 23:12 UTC, sianford approved these changes

2022-02-10 09:29 UTC, DipperTheDan approved these changes

2022-02-10 09:48 UTC, merged

2022-02-10 14:25 UTC, carbonci commented
:tada: This PR is included in version 104.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/104.11.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v104.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: