fix(design-tokens): fix scoped tokens in mfe
Sage/carbon pull request #4791
Opened 2022-02-04 15:18 UTC by mkrds

### Proposed behaviour

This PR fixes an issue where multiple `createGlobalStyle` calls override the already injected styles when multiple MFE's are loaded.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

2022-02-04 15:26 UTC, jamime requested changes

2022-02-04 15:26 UTC, jamime commented on src/style/design-tokens/carbon-scoped-tokens-provider/carbon-scoped-tokens-provider.component.js
>  const CarbonScopedTokensProvider = ({ children }) => (
I think we could delete `TokensProviderWrapper` and add the styles to `CarbonScopedTokensProvider` to reduce the number of components.

2022-02-04 15:29 UTC, samtjo reviewed
`tokensClassName` is also used in Portal and Tooltip - do you need to change the implementations in those components as well?

2022-02-04 15:29 UTC, samtjo commented on src/style/design-tokens/carbon-scoped-tokens-provider/carbon-scoped-tokens-provider.component.js
>  export const tokensClassName = (theme) =>
Is there any need to keep this anymore now that we're not adding the CSS variables to elements with this class?

2022-02-04 16:39 UTC, samtjo approved these changes

2022-02-07 09:50 UTC, jamime approved these changes

2022-02-07 15:46 UTC, samtjo approved these changes

2022-02-07 16:08 UTC, merged

2022-02-07 16:12 UTC, carbonci commented
:tada: This PR is included in version 104.1.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/104.1.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v104.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: