test(multi-action-button): refactor multiactionbutton component
Sage/carbon pull request #4915
Opened 2022-02-28 16:26 UTC by ZhuoyuJin

### Proposed behaviour

Refactor for `Multi Action Button` component to use new `cypress-component-react` framework for testing.

### Current behaviour

Currently we are using the regular `cypress` approach with BDD.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions
- [x] Check if the newly added `multi-action-button.test.js` file passed
- [x] Check if all unnecessary files were deleted

2022-03-01 08:22 UTC, DlgSHi requested changes
`data-role`, `data-element` need to be tested as well. We should test here the `MultiActionButton` instead of the `Button`

2022-03-01 08:22 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +      <MultiActionButton
```suggestion
      <MultiActionButton {...props}>
```

2022-03-01 08:22 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +        size={size}
and remove all props above

2022-03-01 08:22 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +        <Button buttonType="primary" {...props}>
```suggestion
        <Button buttonType="primary">
```

2022-03-01 08:22 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +        <Button buttonType="tertiary" {...props}>
same as above

2022-03-01 08:22 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +    it("should render Multi Action Button with golden border", () => {
it should not trigger golden border `onHover`

2022-03-01 08:22 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +      CypressMountWithProviders(<Button onClick={callback} />);
why we are testing `<Button>`?

2022-03-01 08:22 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +        .trigger("keydown", { force: true }, keyCode("Enter"))
could we not use `{force:true}`? after run the test the `MultiActionButton` is not visible, because the `Accordion` is not expanded

2022-03-03 13:59 UTC, DlgSHi requested changes
We need to add TC to cover:
1. `buttonType` prop
2. `data-element` prop
3. `data-role` prop

2022-03-03 13:59 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +context("Test for Button component", () => {
```suggestion
context("Test for MultiActionButton component", () => {
```

2022-03-03 13:59 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +  describe("Check props for Button component", () => {
```suggestion
  describe("Check props for MultiActionButton component", () => {
```

2022-03-03 13:59 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +      "should render Multi Action Button with different sizes",
```suggestion
      "should render Multi Action Button with %s size",
```

2022-03-03 13:59 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +        <Accordion title="Heading">
use here your own `MultiActionButtonList` component

2022-03-07 12:45 UTC, DlgSHi requested changes

2022-03-07 12:45 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +// eslint-disable-next-line react/prop-types
do we need it here?

2022-03-07 12:45 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +context("Test for MultiActionButton component", () => {
```suggestion
context("Tests for MultiActionButton component", () => {
```

2022-03-07 12:45 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +      "should render Multi Action Button text using %s special characters",
```suggestion
      "should render Multi Action Button text using %s as special characters",
```

2022-03-07 12:45 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +    it("should check Multi Action Button data element", () => {
```suggestion
    it("should check Multi Action Button data element prop", () => {
```

2022-03-07 12:45 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +      "should render Multi Action Button subtext with %s special characters",
```suggestion
      "should render Multi Action Button subtext with %s as special characters",
```

2022-03-07 12:45 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +    it.each([
what about the `color` and `border-color`?

2022-03-07 12:45 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +      "check %s type of multi action button uses %s as a background color",
```suggestion
      "check %s type of Multi action button uses %s as a background color",
```

2022-03-07 12:45 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button.test.js
> +    it.each([
the same is here, what about `color` and `border-color`?

2022-03-07 14:01 UTC, DlgSHi submitted a review, later dismissed

2022-03-07 14:45 UTC, edleeks87 approved these changes

2022-03-07 15:25 UTC, divyajindel commented on src/components/multi-action-button/multi-action-button.test.js
> +      ["small", "32px"],
```suggestion
      ["small", "32px"],
```

2022-03-07 15:32 UTC, DlgSHi approved these changes

2022-03-07 15:39 UTC, merged