test(card): add refactored tests for card component FE-4524
Sage/carbon pull request #4917
Opened 2022-03-01 11:40 UTC by divyajindel

### Proposed behaviour
Refactor for Card component to use new cypress-component-react framework for testing.
I have added test.js and deleted steps.js and feature file.

### Current behaviour

Currently we are using the regular cypress approach with BDD.

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ]  Run npx cypress open-ct to check if there is newly added test.file
- [ ]  Check if the batch-selection.test.js file passed
- [ ]  Compare all tests were moved/refactored from .feature file -> .test.js file
- [ ] Check if all unnecessary files were deleted, including .json file

2022-03-01 12:21 UTC, DlgSHi requested changes

2022-03-01 12:21 UTC, DlgSHi commented on src/components/card/card.test.js
> +  describe("Should check Card component properties", () => {
```suggestion
  describe("should check Card component properties", () => {
```

2022-03-01 12:21 UTC, DlgSHi commented on src/components/card/card.test.js
> +      "Should check %s spacing and padding for Card component ",
```suggestion
      "should check %s spacing and padding for Card component ",
```

2022-03-01 12:21 UTC, DlgSHi commented on src/components/card/card.test.js
> +      "Should check %s string value for Card component",
```suggestion
      "should check %s as children for Card component",
```

2022-03-01 12:21 UTC, DlgSHi commented on src/components/card/card.test.js
> +      "Should check %s width for Card component",
```suggestion
      "should check %s width for Card component",
```

2022-03-01 12:21 UTC, DlgSHi commented on src/components/card/card.test.js
> +      ["small", "24px"],
you can use here a `number`? as:
```suggestion
      ["small", 24],
```

2022-03-01 12:21 UTC, DlgSHi commented on src/components/card/card.test.js
> +      "drag %s Card from the column to %s column",
```suggestion
      "drag %s Card item to the %s column",
```

2022-03-01 12:21 UTC, DlgSHi commented on src/components/card/card.test.js
> +    it("Should check dataRole for Card component", () => {
```suggestion
    it("should check dataRole for Card component", () => {
```

2022-03-01 12:21 UTC, DlgSHi commented on src/components/card/card.test.js
> +    it("Should check interactive for Card component", () => {
```suggestion
    it("should check interactive for Card component", () => {
```

2022-03-01 12:21 UTC, DlgSHi commented on src/components/card/card.test.js
> +      card().click("right", { force: true });
do we need `{force:true}` here ?

2022-03-01 12:21 UTC, DlgSHi commented on src/components/card/card.test.js
> +      "should check %s alignemnet for Card component",
```suggestion
      "should check %s alignment for Card component",
```

2022-03-01 12:21 UTC, DlgSHi commented on src/components/card/card.test.js
> +    it("Should check click action for Card component", () => {
```suggestion
    it("should check click action for Card component", () => {
```

2022-03-03 13:31 UTC, DlgSHi commented on src/components/card/card.test.js
> +const textalignment = ["center", "left", "right"];
```suggestion
const textAlignment = ["center", "left", "right"];
```

2022-03-03 13:31 UTC, DlgSHi commented on src/components/card/card.test.js
> +/* eslint-disable react/prop-types */
do we need this comment here ?

2022-03-04 10:16 UTC, DlgSHi approved these changes

2022-03-04 16:42 UTC, edleeks87 approved these changes

2022-03-04 17:09 UTC, Parsium approved these changes

2022-03-04 23:04 UTC, merged

2022-03-07 08:48 UTC, carbonci commented
:tada: This PR is included in version 104.48.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/104.48.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v104.48.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: