test: accordion
Sage/carbon pull request #4929
Opened 2022-03-03 09:15 UTC by stephenogorman

### Proposed behaviour

Refactor for Accordion component to use new cypress-component-react framework for testing.

### Current behaviour

Currently we are using the regular cypress approach with BDD.
### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

- Run npx cypress open-ct to check if there is newly added test.file
 - Check if the accordion.test.js file passed
 - Compare all tests were moved/refactored from .feature file -> .test.js file
 - Check if all unnecessary files were deleted, including .json file

2022-03-08 09:11 UTC, DlgSHi requested changes
1. We need to delete `accordion-steps.js` and `accordion.json` files.
2. Add TCs to cover all props we haven't tested

2022-03-08 09:11 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +          <AccordionComponent iconAlign={iconAlign}> </AccordionComponent>
We do not need to add a closure if we are not passing the `children` to component
```suggestion
          <AccordionComponent iconAlign={iconAlign} />
```

2022-03-08 09:11 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +      accordionTitleContainer()
the same is here as in line 66

2022-03-08 09:11 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +      accordionTitleContainer(positionOfElement())
no action assertion here

2022-03-11 10:08 UTC, stephenogorman commented on src/components/accordion/accordion.test.js
> +      accordionTitleContainer()
Now checks for accordion-content.

2022-03-11 10:08 UTC, stephenogorman commented on src/components/accordion/accordion.test.js
> +      accordionTitleContainer()
Now checks for accordion-content.

2022-03-11 10:09 UTC, stephenogorman commented on src/components/accordion/accordion.test.js
> +      accordionTitleContainer().click();
Changed to focus.

2022-03-14 14:14 UTC, DlgSHi requested changes
a lot of props are missed

2022-03-14 14:14 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +const AccordionGroups = () => {
```suggestion
const AccordionGroup = () => {
```

2022-03-14 14:14 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +      accordionTitleContainer().click();
you need to click into Header instead of a container

2022-03-14 14:14 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +      accordionTitleContainer().trigger("keydown", keyCode("Enter"));
we need to trigger the main `Accordion`

2022-03-14 14:14 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +  it("should check expansionToggled action was called in Actions Tab on focus", () => {
```suggestion
  it("should check expansionToggled action was called on focus", () => {
```

2022-03-28 12:41 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +            .and("have.css", "border-bottom-color", "rgba(0, 0, 0, 0.9)");
we can pass a second parameter in `(borders, color)` and use it here avoiding using `if` statement as:
```suggestion
            .and("have.css", "border-bottom-color", color);
```

2022-03-28 12:41 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +      (borders) => {
```suggestion
      (borders, color) => {
```

2022-03-28 12:41 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +    it.each([["full"], ["none"]])(
```suggestion
    it.each([
    ["full", "rgb(204, 214, 219)"], 
    ["none", "rgba(0, 0, 0, 0.9)")]
    ])(
```

2022-03-28 12:41 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +        if (defaultExpanded === "true") {
the same is here as for previous TC

2022-03-28 12:41 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +            .and("be.visible");
the same is here, but maybe add third param `visible` or `not.visible`

2022-03-28 12:41 UTC, DlgSHi commented on src/components/accordion/accordion.test.js
> +            "have.css",
the same is here

2022-03-31 06:20 UTC, DlgSHi approved these changes

2022-03-31 16:29 UTC, DianeGit22 approved these changes

2022-04-04 09:25 UTC, merged

2022-04-04 11:01 UTC, carbonci commented
:tada: This PR is included in version 105.1.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/105.1.2)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v105.1.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: