fix(tabs): move onclick handler to button element
Sage/carbon pull request #4950
Opened 2022-03-09 16:39 UTC by robinzigmond

fix #4883

### Proposed behaviour

Moved onclick handler up to button element from tab title content

### Current behaviour

onclick handler is on span element rather than button

### Checklist

- [X] Commits follow our style guide
- [X] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [X] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions
Test tab stories to ensure functionality still works.

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

2022-03-09 17:37 UTC, jamime requested changes
I've requested a updated commit message on Slack.

2022-03-10 11:09 UTC, edleeks87 approved these changes

2022-03-10 11:16 UTC, jamime approved these changes

2022-03-17 16:12 UTC, edleeks87 approved these changes

2022-03-22 11:10 UTC, divyajindel approved these changes

2022-03-22 11:46 UTC, merged

2022-03-22 11:50 UTC, carbonci commented
:tada: This PR is included in version 104.58.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/104.58.2)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v104.58.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: