remove unused variants from Toast and Message components - FE-4234
Sage/carbon pull request #4955
Opened 2022-03-10 11:50 UTC by mkrds

### Proposed behaviour

Fixes #4248 

Removes `maintenance`, `help`, `new` and `default` prop options of `variant` from both Toast and Message components

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

Check Toast and Message stories and prop tables

2022-03-11 10:47 UTC, edleeks87 approved these changes

2022-03-22 10:59 UTC, samtjo commented on src/components/toast/toast.d.ts
> +  variant?: "error" | "info" | "success" | "warning";
Let's tidy this up a bit with a `type ToastVariants = "error" | "info" | "success" | "warning";` which can be shared on both these props here

2022-03-22 15:48 UTC, edleeks87 submitted a review, later dismissed

2022-03-22 16:08 UTC, samtjo approved these changes

2022-03-22 16:44 UTC, jamime requested changes

2022-03-22 18:51 UTC, jamime approved these changes

2022-03-22 20:32 UTC, samtjo submitted a review, later dismissed

2022-03-25 09:40 UTC, samtjo approved these changes

2022-03-25 13:19 UTC, DlgSHi approved these changes

2022-03-25 16:05 UTC, edleeks87 approved these changes

2022-03-28 09:35 UTC, merged

2022-03-28 09:39 UTC, carbonci commented
:tada: This PR is included in version 104.58.8 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/104.58.8)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v104.58.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: