feat(tile): surface variant prop and add deprecation warning for as prop FE-5029
Sage/carbon pull request #4977
Opened 2022-03-18 17:13 UTC by edleeks87

### Proposed behaviour

Adds deprecation warning to `Toast` and `Tile` components
Updates warning for `Button` components to make it clearer which ones are triggering them

### Current behaviour

No warning for `Toast` and `Tile`
`Button` components have generic warning

### Checklist

- [x] Commits follow our style guide
- [x] Unit tests added or updated if required
- [x] Storybook added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

Use sandbox based on linked one below
The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

https://codesandbox.io/s/carbon-quickstart-forked-lvotbt -- don't test this one test the one codesandbox builds using this

2022-03-22 18:57 UTC, jamime requested changes

2022-03-23 10:07 UTC, edleeks87 commented on src/components/toast/toast.component.js
> +      variant: as || variant,
🤦

2022-03-23 18:01 UTC, jamime submitted a review, later dismissed

2022-03-28 09:48 UTC, grabkowski commented
looks fine, I would only change the PR description from
```diff
- Adds deprecation warning to Toast and Tile components
+ Adds deprecation warning for `as` prop in Toast and Tile components
```

2022-03-28 09:49 UTC, grabkowski approved these changes

2022-03-29 19:17 UTC, jamime approved these changes

2022-03-30 06:04 UTC, grabkowski approved these changes

2022-03-30 07:54 UTC, DlgSHi approved these changes

2022-03-30 08:08 UTC, merged