fix(vertical-divider): render component as li element if it is a child of Menu FE-5039
Sage/carbon pull request #4982
Opened 2022-03-21 17:45 UTC by edleeks87

fix #4951

### Proposed behaviour

Wraps `VerticalDivider` in a `MenuContext.Consumer` and uses `as` prop to render wrapper as `li` element if
detected that it is a child of `Menu`
Converts `VerticalDivider` files to TypeScript

### Current behaviour

Renders as a div element
Component files ar JS

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Unit tests added or updated if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

Test that `verticaldivider--in-a-menu` story renders divider as `li` with `aria-hidden=true` and no axe warning exists
Test that other stories that don't have `Menu` render divider as `div` and `aria-hidden=false`
Test that no visual regressions in `VerticalDivider` stories following migration to TS

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

2022-03-22 09:59 UTC, samtjo requested changes

2022-03-22 09:59 UTC, samtjo commented on src/components/menu/menu.component.js
> +              inMenu: true,
You also need to set this in `MenuFullScreen` in the other Provider, otherwise any vertical dividers in a full screen menu won't pick this up

2022-03-22 09:59 UTC, samtjo commented on src/components/vertical-divider/vertical-divider.component.tsx
> +  <MenuContext.Consumer>
Let's consume the context in the functional component way using the `useContext` hook instead, it makes the jsx much cleaner

2022-03-22 09:59 UTC, samtjo commented on src/components/vertical-divider/vertical-divider.component.tsx
> +  height?: number | string;
Good plan adding `height` in, why on earth `h` is the original prop name I have no idea 😅

2022-03-22 09:59 UTC, samtjo commented on src/components/vertical-divider/vertical-divider.style.ts
> +const StyledDivider = styled.div<Partial<VerticalDividerPropTypes>>`
This only needs the `tint` prop from `VerticalDividerPropTypes` - let's use `Pick` to grab only that one from `VerticalDividerPropTypes`

2022-03-22 12:31 UTC, samtjo submitted a review, later dismissed

2022-03-28 09:09 UTC, grabkowski submitted a review, later dismissed

2022-03-29 10:37 UTC, DlgSHi approved these changes

2022-03-29 11:03 UTC, DlgSHi approved these changes

2022-03-29 11:06 UTC, grabkowski approved these changes

2022-03-29 11:16 UTC, samtjo approved these changes

2022-03-29 11:21 UTC, merged

2022-03-29 11:24 UTC, carbonci commented
:tada: This PR is included in version 105.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/105.0.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v105.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: