test(content): add refactored tests for content component FE-4528
Sage/carbon pull request #4994
Opened 2022-03-24 13:57 UTC by divyajindel

### Proposed behaviour
Refactor for Content component to use new cypress-component-react framework for testing.
I have added content.test.js and deleted content.steps.js, content.feature and content.json

### Current behaviour

Currently we are using the regular cypress approach with BDD.

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x]  Run npx cypress open-ct to check if there is newly added test.file
- [x]  Check if the content.test.js file passed
- [x]  Compare all tests were moved/refactored from .feature file -> .test.js file
- [x] Check if all unnecessary files were deleted, including .json file

2022-03-25 06:37 UTC, DlgSHi requested changes
Hi @divyajindel , good job, few small fixes needed:
1. Variant prop need to be covered.
2. Create a const for `special characters`.
3. Create a custom component to avoid duplication in code.

2022-03-25 06:37 UTC, DlgSHi commented on src/components/content/content.test.js
> +    it.each(["mp150ú¿¡üßä", "!@#$%^*()_+-=~[];:.,?{}&\"'<>"])(
we could use this `each` values as a const as usual, and then just use it here and below

2022-03-25 06:37 UTC, DlgSHi commented on src/components/content/content.test.js
> +        <Content title={title} variant={variant}>
we need to check only one param in each test. For example you are asserting here a `title` so there is no need to put here `variant` if you are not checking it later

2022-03-25 06:37 UTC, DlgSHi commented on src/components/content/content.test.js
> +          This is an example of some content
to avoid providing in each test this children we can build the custom component with will render it for us, and just override needed value

2022-03-25 06:37 UTC, DlgSHi commented on src/components/content/content.test.js
> +        <Content title="Title" bodyFullWidth={false}>
`bodyFullWidth={false}` - it is set to `false` by default - we need to check if will be set to `true`

2022-03-25 15:32 UTC, DlgSHi commented on src/components/content/content.test.js
> +        "carbon-content--body-full-width"
I think there is some other things to check than only `class`

2022-03-29 05:29 UTC, DlgSHi approved these changes

2022-03-29 10:04 UTC, sianford commented on src/components/content/content.test.js
> +
Spare line to delete

2022-03-29 12:08 UTC, Parsium approved these changes

2022-03-29 12:41 UTC, sianford approved these changes

2022-03-29 12:43 UTC, merged

2022-03-29 13:11 UTC, carbonci commented
:tada: This PR is included in version 105.0.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/105.0.2)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v105.0.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: