test(number input): add refactored tests for number input FE-4554
Sage/carbon pull request #5021
Opened 2022-04-06 00:15 UTC by sianford

### Proposed behaviour

Refactor for `number-input` component to use new cypress-component-react framework for testing.

### Current behaviour

Currently we are using the regular cypress approach with BDD.

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ] Run npx cypress open-ct to check if there is newly added test.file
- [ ] Check the number.test.js file passed
- [ ] Check all tests have been moved/refactored from .feature file -> .test.js file
- [ ] Check all unnecessary files were deleted, including .json file

2022-04-06 08:33 UTC, DlgSHi requested changes

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +        CypressMountWithProviders(<Number label={labelValue} />);
```suggestion
        CypressMountWithProviders(<NumberInputComponent label={labelValue} />);
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +          <Number label="Number" labelHelp={labelHelpValue} />
```suggestion
          <NumberInputComponent labelHelp={labelHelpValue} />
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +        CypressMountWithProviders(<Number fieldHelp={fieldHelpValue} />);
```suggestion
        CypressMountWithProviders(<NumberInputComponent fieldHelp={fieldHelpValue} />);
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +        CypressMountWithProviders(<Number prefix={prefixValue} />);
```suggestion
        CypressMountWithProviders(<NumberInputComponent prefix={prefixValue} />);
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +        CypressMountWithProviders(<Number placeholder={placeholderValue} />);
```suggestion
        CypressMountWithProviders(<NumberInputComponent placeholder={placeholderValue} />);
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +      CypressMountWithProviders(<Number inputIcon="add" />);
```suggestion
      CypressMountWithProviders(<NumberInputComponent inputIcon="add" />);
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +      CypressMountWithProviders(<Number disabled />);
```suggestion
      CypressMountWithProviders(<NumberInputComponent disabled />);
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +      CypressMountWithProviders(<Number readOnly />);
```suggestion
      CypressMountWithProviders(<NumberInputComponent readOnly />);
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +      commonDataElementInputPreview().type(inputValue, { force: true });
```suggestion
      commonDataElementInputPreview().realType(inputValue);
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +        CypressMountWithProviders(<Number size={size} />);
```suggestion
        CypressMountWithProviders(<NumberInputComponent size={size} />);
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +      CypressMountWithProviders(<Number label="Number" required />);
```suggestion
      CypressMountWithProviders(<NumberInputComponent required />);
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +      CypressMountWithProviders(<Number label="Number" labelInline />);
```suggestion
      CypressMountWithProviders(<NumberInputComponent labelInline />);
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +          <Number label="Number" labelInline labelAlign={alignment} />
```suggestion
          <NumberInputComponent labelInline labelAlign={alignment} />
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +          <Number
```suggestion
          <NumberInputComponent
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +            label="Number"
```suggestion
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +        const now = Date.now();
```suggestion
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +            label="Number"
```suggestion
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +        cy.clock(now);
```suggestion
        cy.clock();
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +            label="Number"
```suggestion
```

2022-04-06 08:33 UTC, DlgSHi commented on src/components/number/number.test.js
> +          // .type(`{${key}}`)
```suggestion
```

2022-04-07 10:10 UTC, sianford commented on src/components/number/number.test.js
> +      getDataElementByValue("label").then(($els) => {
Thanks. I created a `common-steps.js` file in the `support/component-helper` directory for this and other components to call.

2022-04-07 11:26 UTC, DlgSHi approved these changes
Good job, @sianford !

2022-04-07 12:00 UTC, DlgSHi approved these changes

2022-04-07 12:08 UTC, merged

2022-04-07 13:09 UTC, carbonci commented
:tada: This PR is included in version 105.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/105.2.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v105.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: