test(help): add refactored tests for card component FE-4543
Sage/carbon pull request #5081
Opened 2022-04-21 14:54 UTC by divyajindel

### Proposed behaviour
Refactor for Help component to use new cypress-component-react framework for testing.
I have added test.js and deleted steps.js and feature file.

### Current behaviour

Currently we are using the regular cypress approach with BDD.

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x]  Run npx cypress open-ct to check if there is newly added test.file
- [x]  Check if the help.test.js file passed
- [x]  Compare all tests were moved/refactored from .feature file -> .test.js file
- [x] Check if all unnecessary files were deleted, including .json file

2022-04-22 12:37 UTC, DlgSHi requested changes

2022-04-22 12:37 UTC, DlgSHi commented on cypress/locators/help/locators.js
> +  '[data-component="help"] > span[data-component="icon"]';
what is the point of doing this ? why we can't use `icon()` function from `common-locators` ?

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +  describe.only("should check Help component properties", () => {
```suggestion
  describe("should check Help component properties", () => {
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +      "should check %s as children for Message component",
```suggestion
      "should check %s as children for Help component",
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +        helpPreview().click();
should be help called via click?

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +      "should check %s as helpId for Message component",
```suggestion
      "should check %s as helpId for Help component",
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +        helpPreview().should("have.attr", "tabindex", tabIndex);
what we are checking here ?

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +      "should check as prop %s for Message component",
```suggestion
      "should check as prop %s for Help component",
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +          </HelpComponent>
```suggestion
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +          <HelpComponent as={as} isFocused>
```suggestion
          <HelpComponent as={as} isFocused />
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +        helpPreview().should("be.visible");
ok, should be visible but what we are checking here? `as` prop?

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +        helpPreview().should("have.css", position);
and be visible ?

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +      CypressMountWithProviders(<HelpComponent href={link}> </HelpComponent>);
```suggestion
      CypressMountWithProviders(<HelpComponent href={link} />);
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +        cy.wait(500);
why do we need this wait here ?

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +      "should check tooltip id as %s for Message component",
```suggestion
      "should check tooltip id as %s for Help component",
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +          <HelpComponent tooltipId={id} isFocused>
```suggestion
          <HelpComponent tooltipId={id} isFocused />
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +          </HelpComponent>
```suggestion
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +      "should check aria-label as %s for Message component",
```suggestion
      "should check aria-label as %s for Help component",
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +          <HelpComponent isFocused type={icon}>
```suggestion
          <HelpComponent isFocused type={icon} />
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +            {`This is the help component with the ${icon} icon`}
```suggestion
```

2022-04-22 12:37 UTC, DlgSHi commented on src/components/help/help.test.js
> +          </HelpComponent>
```suggestion
```

2022-04-28 16:16 UTC, edleeks87 commented on src/components/help/help.test.js
> +        // helpPreview().should("not.exist");
this can be deleted

2022-04-29 08:52 UTC, DlgSHi requested changes

2022-04-29 08:52 UTC, DlgSHi commented on src/components/help/help.test.js
> +const tabKeyCode = { keyCode: 9, which: 9 };
use `keyCode()` function please instead of declaring the new one

2022-04-29 08:52 UTC, DlgSHi commented on src/components/help/help.test.js
> +          helpPreview().click(-20, -20, { force: true });
why do we need to click here ?

2022-04-29 08:52 UTC, DlgSHi commented on src/components/help/help.test.js
> +        "Warning: The tag <%s> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.%s";
what is `<%s>` here for?

2022-04-29 08:52 UTC, DlgSHi commented on src/components/help/help.test.js
> +          <HelpComponent isFocused tooltipFlipOverrides={[position]}>
Why do we need pass `position` as an array here ?
```suggestion
          <HelpComponent isFocused tooltipFlipOverrides={position}>
```

2022-05-05 14:34 UTC, DlgSHi approved these changes

2022-05-05 16:30 UTC, edleeks87 approved these changes

2022-05-06 08:51 UTC, merged

2022-05-06 09:17 UTC, carbonci commented
:tada: This PR is included in version 106.1.6 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/106.1.6)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v106.1.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: