feat(textarea): modify padding to use design tokens
Sage/carbon pull request #5111
Opened 2022-05-04 09:27 UTC by Parsium

### Proposed behaviour

- Modify inner `InputPresentation` container to use design token for controlling its vertical padding.
- Add label to `Textarea` test story to fix accessibility violation 

![Screenshot 2022-05-04 at 09 41 34](https://user-images.githubusercontent.com/18368713/166648619-a5406deb-fde4-4e39-9371-93d125163f07.png)

### Current behaviour

- The vertical padding is not correct and doesn't use design tokens.

![Screenshot 2022-05-04 at 09 42 03](https://user-images.githubusercontent.com/18368713/166648689-f909a781-1773-4ba1-9165-ae76152c028d.png)

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

(For devs) Both `InputPresentation` and `Input` have css rules for their `min-height`. `Textarea` programmatically controls its height with its internal logic (using `MIN_HEIGHT` constant in `textarea.style.js` on line 10). Since `InputPresentation` controls its own min-height using design tokens, the logic in `Textarea` becomes partially redundant, however we cannot currently modify the `MIN_HEIGHT` constant to use the design token value since we can importing its value as a css custom property and not a js variable. This does not cause an issue but does introduce some complexity to the code related to inputs.

### Testing instructions

- Double check violation no longer exists for `Textarea` test story.
- Double check no regressions have been introduced.

2022-05-04 09:33 UTC, samtjo requested changes
The code changes are fine but the first commit should be a `docs` commit, and it should reference the relevant Github issue rather than the Jira ticket. This means it will be linked to the PR and automatically closed when the PR is merged 👍🏻

2022-05-04 12:26 UTC, samtjo submitted a review, later dismissed

2022-05-05 08:39 UTC, mkrds submitted a review, later dismissed

2022-05-13 09:49 UTC, ZhuoyuJin submitted a review, later dismissed

2022-05-13 10:10 UTC, samtjo approved these changes

2022-05-13 11:10 UTC, mkrds approved these changes

2022-05-16 08:38 UTC, ZhuoyuJin approved these changes

2022-05-16 08:45 UTC, mkrds approved these changes

2022-05-16 09:39 UTC, samtjo approved these changes

2022-05-16 09:42 UTC, merged

2022-05-16 09:46 UTC, carbonci commented
:tada: This PR is included in version 106.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/106.5.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v106.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: