test(Loader Bar): add cypress refactored tests FE-4549
Sage/carbon pull request #5145
Opened 2022-05-12 09:25 UTC by divyajindel

### Proposed behaviour
Refactor for Loader Bar component to use new cypress-component-react framework for testing.
I have added test.js and deleted steps.js and feature file.

### Current behaviour

Currently we are using the regular cypress approach with BDD.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x]  Run npx cypress open-ct to check if there is newly added test.file
- [x]  Check if the loader-bar.test.js file passed
- [x]  Compare all tests were moved/refactored from .feature file -> .test.js file
- [x] Check if all unnecessary files were deleted, including .json file

2022-05-13 10:29 UTC, DlgSHi requested changes
only the commit message need to be fixed like:
`test(loader-bar): add cypress tests`

2022-05-13 12:51 UTC, DlgSHi submitted a review, later dismissed

2022-05-16 06:55 UTC, DlgSHi approved these changes

2022-05-16 10:30 UTC, stephenogorman approved these changes

2022-05-16 10:34 UTC, merged