feat(click-away-wrapper): add ClickAwayWrapper component to internal directory
Sage/carbon pull request #5188
Opened 2022-05-27 15:56 UTC by edleeks87

### Proposed behaviour

Adds `ClickAwayWrapper` component to handle triggering an action if a mousedown/ click event is detected
outside of it

Adds the `ClickAwayWrapper` to enable the `PopoverContainer` to close when a `mousedown` event is
detected from outside of the wrapper boundaries

Adds `ClickAwayWrapper` to `Date` and `Submenu` as well

fix #5017, fix #5158

### Current behaviour

No `ClickAwayWrapper` component exists. `PopoverContainer` does not close when click is outside of it. `Date` and `Submenu` have their own implementations to handle closing when click outside occurs

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

Test Date, Submenu and PopoverContainer stories, clicking inside should not close the components but clicking outside should

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

https://codesandbox.io/s/mystifying-northcutt-c3slyx?file=/src/index.js

2022-05-31 09:59 UTC, Parsium approved these changes

2022-06-06 10:10 UTC, DipperTheDan requested changes

2022-06-06 10:10 UTC, DipperTheDan commented on src/__internal__/click-away-wrapper/click-away-wrapper.spec.tsx
> +  it("removes the event listener on mount", () => {
```suggestion
  it("removes the event listener on unmount", () => {
```

2022-06-06 10:15 UTC, DipperTheDan approved these changes

2022-06-06 10:21 UTC, Parsium submitted a review, later dismissed

2022-06-06 13:52 UTC, DipperTheDan approved these changes

2022-06-10 15:57 UTC, DipperTheDan approved these changes

2022-06-13 12:53 UTC, DlgSHi approved these changes

2022-06-13 13:21 UTC, merged

2022-06-13 13:25 UTC, carbonci commented
:tada: This PR is included in version 107.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/107.1.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v107.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: