test(heading): add cypress tests
Sage/carbon pull request #5330
Opened 2022-07-24 20:31 UTC by divyajindel

### Proposed behaviour
Refactor for heading component to use new cypress-component-react framework for testing.
I have added test.js and deleted steps.js and feature file.

### Current behaviour

Currently we are using the regular cypress approach with BDD.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x]  Run npx cypress open-ct to check if there is newly added test.file
- [x]  Check if the heading.test.js file passed
- [x]  Compare all tests were moved/refactored from .feature file -> .test.js file
- [x] Check if all unnecessary files were deleted, including .json file

2022-07-25 06:28 UTC, DlgSHi requested changes

2022-07-25 06:28 UTC, DlgSHi commented on cypress/locators/heading/index.js
> +export const pillPreview = () => cy.get(PILL_PREVIEW);
we already have the `pill` declared :)

2022-07-25 06:28 UTC, DlgSHi commented on cypress/locators/heading/locators.js
> +export const PILL_PREVIEW = 'span[data-component="pill"]';
we have it already defined  here -> `cypress/locators/pill/index.js`

2022-07-25 09:05 UTC, DlgSHi requested changes
Also you need to delete `heading.feature` and `heading.json`

2022-07-25 12:56 UTC, DlgSHi commented on src/components/heading/heading.test.js
> +        getComponent("pill").should("have.text", pillText);
we already have it defined in file I sent you :) could we just import it from the `pill -> index.js` file ?

2022-07-26 05:27 UTC, DlgSHi submitted a review, later dismissed

2022-07-28 08:39 UTC, Parsium commented on cypress/locators/heading/index.js
> +export const sepratorPreview = () => cy.get(HEADING_PREVIEW).find("div > hr");
```suggestion
export const separatorPreview = () => cy.get(HEADING_PREVIEW).find("div > hr");
```

2022-07-28 08:39 UTC, Parsium commented on src/components/heading/heading.test.js
> +  sepratorPreview,
```suggestion
  separatorPreview,
```

2022-07-29 08:21 UTC, Parsium approved these changes

2022-07-29 09:36 UTC, ZhuoyuJin approved these changes

2022-07-29 09:59 UTC, merged

2022-08-01 09:12 UTC, carbonci commented
:tada: This PR is included in version 109.5.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/109.5.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v109.5.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: