test(duelling-picklist): refactor for cypress tests
Sage/carbon pull request #5437
Opened 2022-09-01 08:34 UTC by stephenogorman

### Proposed behaviour

Refactor Cypress tests for the `Duelling-Picklist` component to use new cypress-component-react framework for testing.
Add `duelling-picklist.test.js`. 

### Current behaviour

Current process is the regular Cypress approach with BDD.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x] Run `npx cypress open --component` to check if there is newly added test.file
- [x] Check if the `duelling-picklist.test.js` file passed
- [x] Check all tests were moved/refactored from .feature file -> .test.js file
- [x] Check all unnecessary files were deleted, including .json file
- [x] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [x] Run `npx cypress run --e2e` to check none of the feature files have regressed

2022-09-01 11:26 UTC, stephenogorman commented
I asked Daniel Dipper about the following props and he informed me that these are props which are controlled internally, so not for the use of consumers, and not something we can verify - they are covered by unit tests:
highlighted
index
groupIndex
listIndex
isLastItem
isLastGroup

Also, 'Disabled' is listed as a prop for Duelling-Picklist, Picklist and PicklistItem, but it is only used in the Duelling-Picklist component - it probably shouldn't be listed for the others.

2022-09-01 13:46 UTC, DlgSHi requested changes

2022-09-01 13:46 UTC, DlgSHi commented on src/components/duelling-picklist/duelling-picklist.test.js
> +      "should verify picklist placeholder = %s",
```suggestion
      "should verify picklist placeholder is set to %s",
```

2022-09-01 13:46 UTC, DlgSHi commented on src/components/duelling-picklist/duelling-picklist.test.js
> +      "should verify picklist item is %s when locked prop is %s",
for `locked` state there is also a colour changing, can you add that assertion as well ?

2022-09-01 13:46 UTC, DlgSHi commented on src/components/duelling-picklist/duelling-picklist.test.js
> +  describe("should render duelling-picklist with external searchbar and access checkbox", () => {
```suggestion
  describe("should render Duelling-Picklist with external searchBar and access checkbox", () => {
```

2022-09-01 13:46 UTC, DlgSHi commented on src/components/duelling-picklist/duelling-picklist.test.js
> +    it("should verify duelling picklist is disabled when access checkox is checked", () => {
```suggestion
    it("should verify Duelling Picklist is disabled when access checkbox is checked", () => {
```

2022-09-01 13:46 UTC, DlgSHi commented on src/components/duelling-picklist/duelling-picklist.test.js
> +    it("should verify duelling picklist is re-enabled when access checkox is unchecked", () => {
```suggestion
    it("should verify Duelling Picklist is re-enabled when access checkbox is unchecked", () => {
```

2022-09-01 13:46 UTC, DlgSHi commented on src/components/duelling-picklist/duelling-picklist.test.js
> +  describe("should render duelling-picklist with items grouped and a picklist divider", () => {
```suggestion
  describe("should render Duelling Picklist with items grouped and a picklist divider", () => {
```

2022-09-01 13:46 UTC, DlgSHi commented on src/components/duelling-picklist/duelling-picklist.test.js
> +context("Testing Duelling-Picklist component", () => {
we should use: 
`Duelling-Picklist` or `Duelling Picklist` - your choice :) 

```suggestion
context("Testing Duelling-Picklist component", () => {
```

2022-09-01 13:46 UTC, DlgSHi commented on src/components/duelling-picklist/duelling-picklist.test.js
> +        .find('[data-element="picklist-group"]')
can we put this locator in `locators.js` file?

2022-09-01 13:46 UTC, DlgSHi commented on src/components/duelling-picklist/duelling-picklist.test.js
> +      addButton(0)
what about `removeButton`?

2022-09-20 08:25 UTC, DlgSHi requested changes
I think you missed few props to cover :)

2022-09-20 11:10 UTC, DlgSHi approved these changes

2022-09-21 12:28 UTC, divyajindel approved these changes

2022-09-21 15:45 UTC, DianeGit22 approved these changes

2022-09-21 15:46 UTC, merged

2022-09-21 16:52 UTC, carbonci commented
:tada: This PR is included in version 110.10.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/110.10.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v110.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: