test(link-preview): refactor for cypress tests
Sage/carbon pull request #5491
Opened 2022-09-21 08:15 UTC by DlgSHi

### Proposed behaviour

1. Refactor Cypress tests for the `Link Preview` component to use new cypress-component-react framework for testing.
Add `link-preview.test.js`. 
2. Implemented new function for checking `goldenOutline` in common steps using jQuery.

### Current behaviour

Current process is the regular Cypress approach with BDD.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ] Run `npx cypress open --component` to check if there is newly added test.file
- [ ] Check if the `link-preview.test.js` file passed
- [ ] Check all tests were moved/refactored from .feature file -> .test.js file
- [ ] Check all unnecessary files were deleted, including .json file
- [ ] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [ ] Run `npx cypress run --e2e` to check none of the feature files have regressed

2022-09-21 12:52 UTC, ZhuoyuJin submitted a review, later dismissed

2022-09-22 08:32 UTC, grabkowski approved these changes

2022-09-22 09:41 UTC, stephenogorman requested changes

2022-09-22 09:41 UTC, stephenogorman commented on src/components/link-preview/link-preview.test.js
> +    it("should call onClick callback when a click event is triggered", () => {
Should this read "should call onClose callback..."?

2022-09-22 09:41 UTC, stephenogorman commented on src/components/link-preview/link-preview.test.js
> +      "should call onClick callback when a keyboard event is triggered",
Same as previous comment.

2022-09-22 10:02 UTC, DlgSHi commented on src/components/link-preview/link-preview.test.js
> +      "should call onClick callback when a keyboard event is triggered",
fixed

2022-09-22 10:03 UTC, stephenogorman approved these changes

2022-09-22 10:07 UTC, grabkowski approved these changes

2022-09-22 10:10 UTC, ZhuoyuJin approved these changes

2022-09-22 10:22 UTC, merged

2022-09-22 11:49 UTC, carbonci commented
:tada: This PR is included in version 110.10.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/110.10.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v110.10.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: