test(accordion): refactor for accessibility tests
Sage/carbon pull request #5520
Opened 2022-10-03 09:11 UTC by DlgSHi

### Proposed behaviour

POC of the possible refactor for the `accessibility` Cypress tests for the `Accordion` component to use new cypress-component-react framework for testing.

Introduced new `custom` command for `a11y` check.

### Current behaviour

Current process is based on building the `json` story for the all list of `component` -> `story`.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ] Run `npx cypress open --component` and check if there are newly added tests for `accessibility`
- [ ] Check if the `accordion.test.js` file passed
- [ ] Check if the proper condition was added to the `cypress/support/accessibility/a11y-utils.js` to ignore re-added tests
- [ ] Check if the `accordion-examples.jsx` file was added
- [ ] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [ ] Run `npx cypress run --e2e` to check none of the feature files have regressed

2022-10-03 09:52 UTC, grabkowski requested changes
could you rewrite `accordion-examples` to `'tsx`, so there will be no need to rewrite it later?

2022-10-03 11:55 UTC, mkrds commented
I think it would be best to keep the test examples in the same folder as the component. Maybe we have to introduce a new file extension like `component.test-cases.tsx` or something like that (and exclude it from build obviously in `scripts/build.js` file)

2022-10-03 13:03 UTC, grabkowski submitted a review, later dismissed

2022-10-04 15:13 UTC, edleeks87 submitted a review, later dismissed

2022-10-10 08:19 UTC, ZhuoyuJin approved these changes

2022-10-12 09:06 UTC, edleeks87 commented on src/components/accordion/accordion.stories.tsx
> +type Validations = "one" | "two" | "three";
```suggestion
type Validations = keyof ValidationObject;
```

2022-10-12 21:31 UTC, sianford submitted a review, later dismissed

2022-10-13 06:16 UTC, grabkowski approved these changes

2022-10-13 07:57 UTC, sianford approved these changes

2022-10-13 08:07 UTC, ZhuoyuJin approved these changes

2022-10-13 08:23 UTC, merged

2022-10-13 12:14 UTC, carbonci commented
:tada: This PR is included in version 111.3.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/111.3.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v111.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: