test(menu): refactor for cypress tests
Sage/carbon pull request #5582
Opened 2022-10-26 16:49 UTC by stephenogorman

### Proposed behaviour

Refactor Cypress tests for the `Menu` component to use new cypress-component-react framework for testing.
Add `menu.test.js`. 

### Current behaviour

Current process is the regular Cypress approach with BDD.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x] Run `npx cypress open --component` to check if there is newly added test.file
- [x] Check if the `menu.test.js` file passed
- [x] Check all tests were moved/refactored from .feature file -> .test.js file
- [x] Check all unnecessary files were deleted, including .json file
- [x] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [x] Run `npx cypress run --e2e` to check none of the feature files have regressed

2022-10-27 10:45 UTC, DlgSHi requested changes
I think those TC are missing:
1. Scenario: Check that inner Menu without link is NOT available with tabbing in Fullscreen Menu
    Given I open "Menu Test" component page "menu-full-screen-story"
    When I continue to hit Tab key 8 times
    Then inner menu without active redirection is not focused

2. Scenario: If there is a Menu Item with a very long label inside a submenu, check that the width of the whole submenu is determined by this submenu item
    Given I open "Menu Test" component page "long-labels-story"
    When I hover over "first" expandable Menu component
    Then width of submenu should equal the width of the "second" submenu item

3. Scenario: If there is a Menu Item with a submenu that has a very long label, check the width of the whole submenu is determined by this parent item
    Given I open "Menu Test" component page "long-labels-story"
    When I hover over "second" expandable Menu component
    Then width of submenu should equal the width of "second" expandable Menu component

4. And few props are missing as well:
 - href, 
 - rel, 
 - parent, 
 - parentVariant

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +          `${after}px`
do we need this `after` if it is still `0` for both examples?

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +          {["white"].map((menuType) => (
do we need a `.map` here if we are using only one item in array?

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +          {["white"].map((menuType) => (
same question here about the `.map`

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +    it.each([
we can wrap this test into a separate `describe` and pass what exactly `type` we are passing, as I did in line 104 in `pages.test.js` file

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +      "should verify Menu height is set by height prop when passed as an integer or a string",
same here for a type, we can actually wrap all these tests where we are passing this sentence `when passed as an integer or a string`

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +      menu("box").should("have.css", "flex-shrink", shrinkText);
why here we have `menu("box")` but everywhere else just `menu()` ?

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +            {["white"].map((menuType) => (
same here for the `.map(...)`

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +            {["white"].map((menuType) => (
same here for the `.map(...)`

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +          expect(callback).to.have.been.called;
```suggestion
          expect(callback).to.have.been.calledOnce;
```

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +            expect(callback).to.have.been.called;
```suggestion
          expect(callback).to.have.been.calledOnce;
```

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +          expect(callback).to.have.been.called;
```suggestion
          expect(callback).to.have.been.calledOnce;
```

2022-10-27 10:45 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +          expect(callback).to.have.been.called;
```suggestion
          expect(callback).to.have.been.calledOnce;
```

2022-10-27 13:57 UTC, ZhuoyuJin commented on src/components/menu/menu.test.js
> +    });
Can we combine this test case with the above test case using it.each["downarrow", "uparrow"]?

2022-10-27 13:59 UTC, ZhuoyuJin commented on src/components/menu/menu.test.js
> +  describe("should render Menu component", () => {
could you please change it to something like "check props for Menu component"

2022-10-28 14:48 UTC, stephenogorman commented on src/components/menu/menu.test.js
> +        cy.viewport(1200, 800);
Test will fail when boolVal is true if we don't have the viewport.

2022-10-28 14:51 UTC, stephenogorman commented
> I think those TC are missing:
> 
>     1. Scenario: Check that inner Menu without link is NOT available with tabbing in Fullscreen Menu
>        Given I open "Menu Test" component page "menu-full-screen-story"
>        When I continue to hit Tab key 8 times
>        Then inner menu without active redirection is not focused
> 
>     2. Scenario: If there is a Menu Item with a very long label inside a submenu, check that the width of the whole submenu is determined by this submenu item
>        Given I open "Menu Test" component page "long-labels-story"
>        When I hover over "first" expandable Menu component
>        Then width of submenu should equal the width of the "second" submenu item
> 
>     3. Scenario: If there is a Menu Item with a submenu that has a very long label, check the width of the whole submenu is determined by this parent item
>        Given I open "Menu Test" component page "long-labels-story"
>        When I hover over "second" expandable Menu component
>        Then width of submenu should equal the width of "second" expandable Menu component
> 
>     4. And few props are missing as well:
> 
> 
>     * href,
> 
>     * rel,
> 
>     * parent,
> 
>     * parentVariant

I added tests for scenario 1 and the props which mere missing. I think scenarios 2 & 3 were actually covered, but the titles weren't clear enough. I have changed those now to:
"should verify if there is a Menu Item with a very long label inside a submenu, check that the width of the whole submenu is determined by this submenu item"
&
"should verify if there is a Menu Item with a submenu that has a very long label, check the width of the whole submenu is determined by this parent item"

2022-11-01 16:17 UTC, ZhuoyuJin submitted a review, later dismissed

2022-11-02 12:39 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +      for (let i = 0; i < 4; i++) {
```suggestion
      for (let i = 0; i < position.length; i++) {
```

2022-11-02 12:39 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +    const menuClick = (position) => {
why we can't move this into `beforeEach` as well?

2022-11-02 14:14 UTC, DlgSHi commented on src/components/menu/menu.test.js
> +            {["white"].map((menuType) => (
not fixed

2022-11-03 07:21 UTC, DlgSHi approved these changes

2022-11-03 08:44 UTC, merged

2022-11-03 10:03 UTC, carbonci commented
:tada: This PR is included in version 111.8.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/111.8.3)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v111.8.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: