test(tile): add cypress tests
Sage/carbon pull request #5583
Opened 2022-10-26 16:59 UTC by divyajindel

### Proposed behaviour
Refactor for tile component to use new cypress-component-react framework for testing.
I have added test.js and deleted steps.js and feature file.

### Current behaviour

Currently we are using the regular cypress approach with BDD.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x]  Run npx cypress open --component to check if there is newly added test.file
- [x]  Check if the tile.test.js file passed
- [x]  Compare all tests were moved/refactored from .feature file -> .test.js file
- [x] Check if all unnecessary files were deleted, including .json file

2022-10-27 11:06 UTC, DlgSHi requested changes
`variant` for TileFooter is not covered, no tests for TileFooter 
`w` for Dl is not covered as well

2022-10-27 13:28 UTC, DlgSHi submitted a review, later dismissed

2022-10-27 14:27 UTC, ZhuoyuJin commented on src/components/tile/tile.test.js
> +          .and("have.css", "width", `${ddWidth}px`);
Don't we need checking "margin-left" here? ".and("have.css", "margin-left", "0px");"

2022-10-27 15:50 UTC, ZhuoyuJin approved these changes

2022-10-28 10:54 UTC, nineteen88 approved these changes

2022-10-28 14:22 UTC, ZhuoyuJin approved these changes

2022-10-28 14:32 UTC, merged

2022-10-31 09:46 UTC, carbonci commented
:tada: This PR is included in version 111.8.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/111.8.2)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v111.8.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: