test(textarea): refactor for cypress tests
Sage/carbon pull request #5586
Opened 2022-10-28 11:51 UTC by DlgSHi

### Proposed behaviour

Refactor Cypress tests for the `Textarea` component to use new cypress-component-react framework for testing.
Add `textarea.test.js`. 

- removed few unnecessary `json` files

### Current behaviour

Current process is the regular Cypress approach with BDD.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ] Run `npx cypress open --component` to check if there is newly added test.file
- [ ] Check if the `textarea.test.js` file passed
- [ ] Check all tests were moved/refactored from .feature file -> .test.js file
- [ ] Check all unnecessary files were deleted, including .json file
- [ ] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [ ] Run `npx cypress run --e2e` to check none of the feature files have regressed

2022-10-28 16:12 UTC, divyajindel requested changes

2022-10-28 16:14 UTC, divyajindel commented
tooltipMessage & children props are not covered for Textarea.

2022-10-31 11:45 UTC, DlgSHi commented on src/components/textarea/textarea.test.js
> +    );
what is the point of this change? we need to assert the `string` which contains `${value}px`

2022-10-31 11:45 UTC, DlgSHi commented on src/components/textarea/textarea.test.js
> +      }
what is the point of this change? we need to assert the `string` which contains `${value}px`

2022-10-31 11:45 UTC, DlgSHi commented on src/components/textarea/textarea.test.js
> +      }
what is the point of this change? we need to assert the `string` which contains `${value}px`

2022-10-31 11:54 UTC, DlgSHi commented on src/components/textarea/textarea.test.js
> +      ["11", "10", "rgb(203, 55, 74)"],
this will be converted to a `string` as well here 
`${charactersUsed}/${limit}`

2022-10-31 11:54 UTC, DlgSHi commented on src/components/textarea/textarea.test.js
> +      ["10", "10"],
as above

2022-10-31 11:55 UTC, DlgSHi commented on src/components/textarea/textarea.test.js
> +      [10000, "10"],
it is not used anywhere in test? so what's the point?

2022-10-31 11:56 UTC, DlgSHi commented on src/components/textarea/textarea.test.js
> +      ["block", "401"],
good spot, will change this

2022-11-01 14:13 UTC, ZhuoyuJin requested changes
Could we add a test case or tooltipMessage prop?

2022-11-02 13:00 UTC, divyajindel approved these changes

2022-11-02 13:07 UTC, ZhuoyuJin approved these changes

2022-11-02 13:47 UTC, sianford approved these changes

2022-11-02 15:03 UTC, merged

2022-11-03 10:03 UTC, carbonci commented
:tada: This PR is included in version 111.8.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/111.8.3)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v111.8.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: