test(switch): refactor for cypress tests
Sage/carbon pull request #5601
Opened 2022-11-09 15:51 UTC by stephenogorman

### Proposed behaviour

Refactor Cypress tests for the `Switch` component to use new cypress-component-react framework for testing.
Add `switch.test.js`. 

### Current behaviour

Current process is the regular Cypress approach with BDD.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x] Run `npx cypress open --component` to check if there is newly added test.file
- [x] Check if the `switch.test.js` file passed
- [x] Check all tests were moved/refactored from .feature file -> .test.js file
- [x] Check all unnecessary files were deleted, including .json file
- [x] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [x] Run `npx cypress run --e2e` to check none of the feature files have regressed

2022-11-10 11:11 UTC, DlgSHi requested changes
One TC with `defaultChecked` is missing

2022-11-10 11:11 UTC, DlgSHi commented on src/components/switch/switch.test.js
> +      "should render CheckboxComponent component with tooltip positioned to the %s",
checkboxComponent?

2022-11-10 11:11 UTC, DlgSHi commented on src/components/switch/switch.test.js
> +      switchInput()
I think we can add a TC with toggling `Switch` with `Space` keyboard

2022-11-11 14:26 UTC, DlgSHi submitted a review, later dismissed
LGTM only squash the commits :)

2022-11-11 16:34 UTC, DianeGit22 approved these changes

2022-11-11 16:35 UTC, merged

2022-11-14 10:16 UTC, carbonci commented
:tada: This PR is included in version 111.9.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/111.9.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v111.9.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: