Cypress refactor sidebar
Sage/carbon pull request #5611
Opened 2022-11-15 10:49 UTC by stephenogorman

### Proposed behaviour

Add Cypress tests for the `Sidebar` component to use new cypress-component-react framework for testing.
Add `sidebar.test.js`. 

### Current behaviour

Current process is the regular Cypress approach with BDD

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ] Run `npx cypress open --component` to check if there is newly added test.file
- [ ] Check if the `sidebar.test.js` file passed
- [ ] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [ ] Run `npx cypress run --e2e` to check none of the feature files have regressed

2022-11-15 12:55 UTC, DlgSHi requested changes
focusableSelectors prop is not covered

2022-11-15 12:55 UTC, DlgSHi commented on src/components/sidebar/sidebar.test.js
> +      <Button onClick={function noRefCheck() {}}>Open sidebar</Button>
do we need this `<Button>` here?

2022-11-15 12:55 UTC, DlgSHi commented on src/components/sidebar/sidebar.test.js
> +      sidebarPreview().should("have.css", "right", `${right}px`);
```suggestion
      .and("have.css", "right", `${right}px`);
```

2022-11-15 12:55 UTC, DlgSHi commented on src/components/sidebar/sidebar.test.js
> +    it("verify Sidebar has aria-label 'cypress-data'", () => {
```suggestion
    it("verify Sidebar has aria-label cypress-data", () => {
```

2022-11-15 12:55 UTC, DlgSHi commented on src/components/sidebar/sidebar.test.js
> +      ["extra-small", 214],
can we use here `src/components/sidebar/sidebar.config.ts` ?

2022-11-15 12:55 UTC, DlgSHi commented on src/components/sidebar/sidebar.test.js
> +    it("verify Sidebar has role 'cypress-data'", () => {
```suggestion
    it("verify Sidebar has role cypress-data", () => {
```

2022-11-15 12:55 UTC, DlgSHi commented on src/components/sidebar/sidebar.test.js
> +    it("verify Sidebar has data-element 'cypress-data'", () => {
```suggestion
    it("verify Sidebar has data-element cypress-data", () => {
```

2022-11-15 12:55 UTC, DlgSHi commented on src/components/sidebar/sidebar.test.js
> +    it("verify Sidebar has data-role 'cypress-data'", () => {
```suggestion
    it("verify Sidebar has data-role cypress-data", () => {
```

2022-11-15 12:55 UTC, DlgSHi commented on src/components/sidebar/sidebar.test.js
> +    ])("verify Sidebar with disableEscKey prop %s", (boolVal, state) => {
```suggestion
    ])("verify Sidebar with disableEscKey prop set to %s", (boolVal, state) => {
```

2022-11-15 12:55 UTC, DlgSHi commented on src/components/sidebar/sidebar.test.js
> +    ])("verify Sidebar with open prop %s", (boolVal, state) => {
```suggestion
    ])("verify Sidebar with open prop set to %s", (boolVal, state) => {
```

2022-11-15 12:55 UTC, DlgSHi commented on src/components/sidebar/sidebar.test.js
> +      callback = cy.stub();
do we need this `describe` and `before` for only 1 test?

2022-11-15 12:55 UTC, DlgSHi commented on src/components/sidebar/sidebar.test.js
> +    it("should call onClick callback when a click event is triggered", () => {
```suggestion
    it("should call onCancel callback when a click event is triggered", () => {
```

2022-11-15 15:01 UTC, DlgSHi requested changes
Still no tests for `focusableSelectors` prop

2022-11-16 14:41 UTC, DlgSHi approved these changes
LGTM, only squash the commits

2022-11-16 17:37 UTC, DianeGit22 approved these changes

2022-11-18 09:39 UTC, merged

2022-11-21 10:37 UTC, carbonci commented
:tada: This PR is included in version 111.10.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/111.10.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v111.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: