test(form): add cypress tests
Sage/carbon pull request #5620
Opened 2022-11-17 19:24 UTC by divyajindel

### Proposed behaviour
Refactor for form component to use new cypress-component-react framework for testing.
I have added test.js and deleted steps.js and feature file.

### Current behaviour

Currently we are using the regular cypress approach with BDD.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x]  Run npx cypress open --component to check if there is newly added test.file
- [x]  Check if the form.test.js file passed
- [x]  Compare all tests were moved/refactored from .feature file -> .test.js file
- [x] Check if all unnecessary files were deleted, including .json file

2022-11-20 23:07 UTC, ZhuoyuJin requested changes

2022-11-21 08:42 UTC, DlgSHi requested changes

2022-11-21 08:42 UTC, DlgSHi commented on cypress/locators/form/locators.js
> +
why do we need this empty line?

2022-11-21 08:42 UTC, DlgSHi commented on src/components/form/form.test.js
> +  FormPreview,
```suggestion
  formPreview,
```

2022-11-21 08:42 UTC, DlgSHi commented on cypress/locators/form/index.js
> +export const FormPreview = () => cy.get(FORM_COMPONENT);
```suggestion
export const formPreview = () => cy.get(FORM_COMPONENT);
```

2022-11-21 08:42 UTC, DlgSHi commented on src/components/form/form.test.js
> +        FormPreview().then(($el) => {
```suggestion
        formPreview().then(($el) => {
```

2022-11-21 08:42 UTC, DlgSHi commented on src/components/form/form.test.js
> +          FormPreview().should("have.attr", "noValidate");
```suggestion
          formPreview().should("have.attr", "noValidate");
```

2022-11-21 08:42 UTC, DlgSHi commented on src/components/form/form.test.js
> +          FormPreview().should("not.have.attr", "noValidate");
```suggestion
          formPreview().should("not.have.attr", "noValidate");
```

2022-11-21 08:42 UTC, DlgSHi commented on src/components/form/form.test.js
> +      it("should call onSubmit callback when a click event is triggered", () => {
if we have only 1 test for `onSubmit` why we need to create a separate `describe` block?
Even if we've created it why we need to put all other tests here?

2022-11-21 08:42 UTC, DlgSHi commented on src/components/form/form.test.js
> +        FormPreview()
```suggestion
        formPreview()
```

2022-11-21 08:42 UTC, DlgSHi commented on src/components/form/form.test.js
> +            <Button onClick={() => console.log("other")} ml={2}>
```suggestion
            <Button onClick={() => {}} ml={2}>
```

2022-11-21 08:42 UTC, DlgSHi commented on src/components/form/form.test.js
> +        FormPreview().should("have.css", "height", height);
```suggestion
        formPreview().should("have.css", "height", height);
```

2022-11-21 13:15 UTC, DlgSHi requested changes

2022-11-21 13:15 UTC, DlgSHi commented on src/components/form/form.test.js
> +            <Button onClick={() => console.log("cancel")} ml={2}>
this is still not fixed
```suggestion
            <Button onClick={() => {}} ml={2}>
```

2022-11-21 13:15 UTC, DlgSHi commented on src/components/form/form.test.js
> +        if (noValidate === true) {
```suggestion
        if (noValidate) {
```

2022-11-21 13:15 UTC, DlgSHi commented on src/components/form/form.test.js
> +let callback;
we can delete this and just use only in test with `callback`

2022-11-21 13:15 UTC, DlgSHi commented on src/components/form/form.test.js
> +      CypressMountWithProviders(<FormComponent onSubmit={callback} />);
```suggestion
      const callback = cy.stub();

      CypressMountWithProviders(<FormComponent onSubmit={callback} />);
```

2022-11-21 14:15 UTC, DlgSHi approved these changes

2022-11-21 14:41 UTC, ZhuoyuJin approved these changes

2022-11-21 17:04 UTC, merged

2022-11-23 09:01 UTC, carbonci commented
:tada: This PR is included in version 111.12.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/111.12.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v111.12.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: