test(icon-button): add cypress tests
Sage/carbon pull request #5630
Opened 2022-11-22 11:31 UTC by DlgSHi

### Proposed behaviour
- Add Cypress tests for the `Icon-Button` component to use new cypress-component-react framework for testing.
- Add `icon-button.test.js`. 

### Current behaviour
No tests for `Icon-Button` component

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ] Run `npx cypress open --component` to check if there is newly added test.file
- [ ] Check if the `icon-button.test.js` file passed
- [ ] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [ ] Run `npx cypress run --e2e` to check none of the feature files have regressed

2022-11-22 11:57 UTC, divyajindel commented on src/components/icon-button/icon-button.test.js
> +    it("should call onAction callback when a clcik event is triggered", () => {
```suggestion
    it("should call onAction callback when a click event is triggered", () => {
```

2022-11-22 12:18 UTC, ZhuoyuJin requested changes

2022-11-22 12:18 UTC, ZhuoyuJin commented on src/components/icon-button/icon-button.test.js
> +      icon().and("be.visible");
icon().should("be.visible");

2022-11-22 13:30 UTC, ZhuoyuJin approved these changes

2022-11-23 07:48 UTC, merged

2022-11-23 09:01 UTC, carbonci commented
:tada: This PR is included in version 111.12.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/111.12.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v111.12.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: