test: update cypress dependencies
Sage/carbon pull request #5752
Opened 2023-01-16 08:25 UTC by DlgSHi

### Proposed behaviour

- update dependencies
- update `docker-compose.yml` file

### Current behaviour

- an old version of cypress

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions
- [x] All tests should pass

2023-01-16 11:42 UTC, stephenogorman commented on src/components/advanced-color-picker/advanced-color-picker.test.js
> +      "should close AdvancedColorPicker using Space on selected color",
"should close AdvancedColorPicker using %s on selected color"

2023-01-16 11:42 UTC, stephenogorman commented on src/components/flat-table/flat-table.test.js
> +    it.only("should render Flat Table Header and Cells with custom vertical header and body borders", () => {
it("should render Flat Table Header and Cells with custom vertical header and body borders", () => {

2023-01-16 11:42 UTC, stephenogorman commented on src/components/flat-table/flat-table.test.js
> +        // });
should commented lines be here?

2023-01-16 14:50 UTC, stephenogorman approved these changes

2023-01-17 09:13 UTC, grabkowski requested changes
I think that the commit message and PR title should be:
`test: update cypress dependencies`

2023-01-17 10:00 UTC, grabkowski approved these changes

2023-01-17 10:03 UTC, stephenogorman approved these changes

2023-01-17 10:04 UTC, ZhuoyuJin approved these changes

2023-01-17 10:17 UTC, merged

2023-01-18 09:31 UTC, carbonci commented
:tada: This PR is included in version 114.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/114.1.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v114.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: