test(card): add accessibility tests
Sage/carbon pull request #5781
Opened 2023-01-26 11:21 UTC by stephenogorman

### Proposed behaviour
- Add `accessibility` Cypress tests for the `Card` component to use the new cypress-component-react framework for testing.
- Refactor `card.stories.mdx` and `card.stories.test.mdx` to corresponding `*.tsx`files.

### Current behaviour
Old approach for accessibility tests

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ] Run `npx cypress open --component` to check if there is newly added test.file
- [ ] Check if the `card.test.js` file passed
- [ ] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [ ] Run `npx cypress run --e2e` to check none of the feature files have regressed
- [ ] Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that `action-popover` tests are not running twice.

2023-01-31 07:12 UTC, DlgSHi requested changes

2023-01-31 07:12 UTC, DlgSHi commented on src/components/card/card-test.stories.tsx
> +export const DefaultStory: ComponentStory<typeof Card> = (args) => {
add please an `includeStories` parameter :)

2023-01-31 14:10 UTC, DlgSHi submitted a review, later dismissed

2023-01-31 15:23 UTC, divyajindel approved these changes

2023-01-31 15:24 UTC, merged

2023-02-01 12:10 UTC, carbonci commented
:tada: This PR is included in version 114.7.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/114.7.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v114.7.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: