test(profile): add accessibility tests
Sage/carbon pull request #5789
Opened 2023-01-31 00:02 UTC by divyajindel

### Proposed behaviour
- Add `accessibility` Cypress tests for the `Profile` component to use the new cypress-component-react framework for testing.

### Current behaviour
Old approach for accessibility tests

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x] Run `npx cypress open --component` to check if there are newly added tests
- [x] Check if the `profile.test.js` file passed
- [x] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [x] Run `npx cypress run --e2e` to check none of the feature files have regressed
- [x] Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that `alert` tests are not running twice.

2023-01-31 07:55 UTC, DlgSHi requested changes

2023-01-31 07:55 UTC, DlgSHi commented on src/components/profile/profile.test.js
> +const ProfileComponent = ({ ...props }) => {
why we can't move this as we agreed into `profile-test.stories.tsx`

2023-02-01 10:12 UTC, DlgSHi requested changes

2023-02-01 10:12 UTC, DlgSHi commented on src/components/profile/profile-test.stories.tsx
> +  includeStoris: "DefaultStory",
```suggestion
  includeStories: "DefaultStory",
```

2023-02-02 10:09 UTC, DlgSHi approved these changes

2023-02-02 13:18 UTC, Parsium submitted a review, later dismissed

2023-02-02 14:24 UTC, Parsium approved these changes

2023-02-02 14:27 UTC, DlgSHi approved these changes

2023-02-02 14:31 UTC, merged

2023-02-03 15:15 UTC, carbonci commented
:tada: This PR is included in version 114.8.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/114.8.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v114.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: