test(pod): refactor for accessibility tests
Sage/carbon pull request #5838
Opened 2023-02-15 09:47 UTC by ZhuoyuJin

### Proposed behaviour
- Add `accessibility` Cypress tests for the `Pod` component to use the new cypress-component-react framework for testing.
- Move testing component to the `pod-test.stories.tsx`

### Current behaviour
Old approach for accessibility tests

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ] Run `npx cypress open --component` to check if there are newly added tests
- [ ] Check if the `pod.test.js` file passed
- [ ] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [ ] Run `npx cypress run --e2e` to check none of the feature files have regressed
- [ ] Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that `Pod` tests are not running twice.

2023-02-15 10:16 UTC, DlgSHi requested changes

2023-02-15 10:16 UTC, DlgSHi commented on src/components/pod/pod-test.stories.tsx
> +  includeStories: "DefaultStory",
```suggestion
  includeStories: "Default",
```

2023-02-15 13:32 UTC, DipperTheDan approved these changes

2023-02-15 13:56 UTC, merged

2023-02-16 15:35 UTC, carbonci commented
:tada: This PR is included in version 114.14.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/114.14.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v114.14.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: