Icon accessibility
Sage/carbon pull request #5867
Opened 2023-02-26 23:54 UTC by divyajindel

### Proposed behaviour

- Add `accessibility` Cypress tests for the `Icon` component to use the new cypress-component-react framework for testing.
- Move testing component to the `icon-test.stories.tsx`

### Current behaviour
Old approach for accessibility tests

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x] Run `npx cypress open --component` to check if there is newly added test.file
- [x] Check if the `icon.test.js` file passed
- [x] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [x] Run `npx cypress run --e2e` to check none of the feature files have regressed
- [x] Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that `Icon` tests are not running twice.

2023-02-27 14:35 UTC, ZhuoyuJin submitted a review, later dismissed

2023-02-28 10:17 UTC, DlgSHi requested changes

2023-03-01 07:57 UTC, DlgSHi requested changes

2023-03-01 07:57 UTC, DlgSHi commented on src/components/icon/icon-test.stories.tsx
> +        marginLeft: "300px",
I meant to use like: 

`cy.mount(<<Box
       style={{
         marginLeft: "300px",
         marginRight: "64px",
         marginTop: "64px",
         marginBottom: "64px",
       }}
     ><IconComponent/></Box>
)`

2023-03-01 14:45 UTC, DlgSHi approved these changes

2023-03-01 15:34 UTC, ZhuoyuJin approved these changes

2023-03-01 16:17 UTC, Parsium commented on src/components/icon/icon-test.stories.tsx
> +  includeStories: "Default",
```suggestion
  excludeStories: ["IconComponent", "IconTooltipComponent"]
```

2023-03-02 08:48 UTC, DlgSHi approved these changes

2023-03-02 08:49 UTC, merged

2023-03-02 10:41 UTC, carbonci commented
:tada: This PR is included in version 114.17.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/114.17.4)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v114.17.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: