test(number-input): refactor accessibility tests
Sage/carbon pull request #5878
Opened 2023-03-01 09:29 UTC by ZhuoyuJin

### Proposed behaviour
- Add `accessibility` Cypress tests for the `Number Input` component to use the new cypress-component-react framework for testing.

### Current behaviour
Old approach for accessibility tests

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [x] Run `npx cypress open --component` to check if there are newly added tests
- [x] Check if the `number.test.js` file passed
- [x] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [x] Run `npx cypress run --e2e` to check none of the feature files have regressed
- [x] Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that `Number` tests are not running twice.

2023-03-01 10:16 UTC, DlgSHi requested changes

2023-03-01 10:16 UTC, DlgSHi commented on src/components/number/number.test.js
> +
we are not checking this properly - we need to type something over limit to check accessibility

2023-03-01 10:16 UTC, DlgSHi commented on src/components/number/number.test.js
> +
same here

2023-03-01 10:16 UTC, DlgSHi commented on src/components/number/number.test.js
> +      "should use %s as size and render Number with %s as height",
we don't have a second parameter here so second `%s` will be empty

2023-03-01 10:16 UTC, DlgSHi commented on src/components/number/number.test.js
> +  describe("check accessibility for Number component", () => {
isn't it easier to import just all stories from `number.stories.tsx` file? and just check it?

2023-03-02 12:25 UTC, DlgSHi approved these changes

2023-03-02 15:05 UTC, DipperTheDan approved these changes

2023-03-02 15:21 UTC, merged

2023-03-03 07:53 UTC, carbonci commented
:tada: This PR is included in version 114.17.5 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/114.17.5)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v114.17.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: