Sage/DSY-2333: ShowEditPod Storybook Update
Sage/carbon pull request #5895
Opened 2023-03-06 14:42 UTC by DobroTora

### Proposed behaviour

### Current behaviour

### Checklist

- [ ] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

2023-03-06 17:18 UTC, mkrds commented
I think it might be worth adding a deprecation message to the component as well. This will allow developers to see a message in the console that informs them about the upcoming deprecation.

2023-03-06 18:05 UTC, DobroTora commented
> I think it might be worth adding a deprecation message to the component as well. This will allow developers to see a message in the console that informs them about the upcoming deprecation.
> 
> Here's an example of how we used to do it previously:
> 
> https://github.com/Sage/carbon/blob/d334623193cd13bbf2976d5a34d3bd635fc029b7/src/components/grouped-character/grouped-character.component.tsx#L75

Definitely. I first want to check with my team that this is how they would like it to look like.

2023-03-10 10:54 UTC, Parsium commented on src/components/show-edit-pod/show-edit-pod.stories.mdx
> +We've deprecated ShowEditPod. It's no longer available in the Product Design System or Figma library and we recommend that you do not use it in new products. See Quick Start section for alternatives.
```suggestion
We've deprecated ShowEditPod. It's no longer available in the Product Design System or Figma library and we recommend that you do not use it in new products. See Related Components section for alternatives.
```

2023-03-10 12:59 UTC, Parsium approved these changes

2023-03-21 15:30 UTC, edleeks87 requested changes
You've added a superfluous `inputRef` prop. Can we add a test for deprecation warning please, mainly to confirm that it only fires once, something like the below should work but feel free to ping me on slack if you need a hand with it 👍 

```
 const mockConsole = jest
      .spyOn(global.console, "warn")
      .mockImplementation(() => undefined);
      
mount(
  <>
  <ShowEditPod />
  <ShowEditPod />
  </>
)

expect(mockConsole).toHaveBeenCalledTimes(1)
expect(mockConsole).toHaveBeenCalledWith("The ShowEditPod component is deprecated and will soon be removed. Please use alternatives such as the Fieldset, Form or Pod components instead")

mockConsole.mockRestore();
```

2023-03-21 15:30 UTC, edleeks87 commented on src/components/show-edit-pod/show-edit-pod.component.js
> +  inputRef,
You don't need this prop, it will never be set as it's not a part of this component's interface

2023-03-21 16:54 UTC, DobroTora commented on src/components/show-edit-pod/show-edit-pod.component.js
> +      "The ShowEditPod component is deprecated and will soon be removed. Please use alternatives: Fieldset, Form, Pod components instead."
It does indeed.

2023-03-23 10:40 UTC, Parsium reviewed
A couple of minor wording suggestions from me, but they aren't essential 👍🏼

2023-03-23 10:40 UTC, Parsium commented on src/components/show-edit-pod/show-edit-pod.spec.js
> +  it("when user is trying to use a component, deprecation warning is raised in the console", () => {
Just a minor tweak in wording :)
```suggestion
  it("when user uses the component, a deprecation warning is raised in the console", () => {
```

2023-03-23 10:40 UTC, Parsium commented on src/components/show-edit-pod/show-edit-pod.stories.mdx
> +We've deprecated ShowEditPod. It's no longer available in the Product Design System or Figma library and we recommend that you do not use it in new products. See Related Components section for altern
What do you think about this small change to make the message more concise? This is really minor so I'm happy to accept how it is currently if you disagree :)

```suggestion
We've deprecated ShowEditPod. It's no longer available in the Design System and we recommend that you do not use it in new products. See Related Components section for alternatives.
```

2023-03-28 12:19 UTC, Parsium approved these changes

2023-03-30 09:10 UTC, edleeks87 commented on src/components/show-edit-pod/show-edit-pod.component.js
> +let deprecateInputRefWarnTriggered = false;
There is no input ref

```suggestion
let deprecateWarnTriggered = false;
```

2023-03-30 09:10 UTC, edleeks87 commented on src/components/show-edit-pod/show-edit-pod.component.js
> +  if (!deprecateInputRefWarnTriggered) {
```suggestion
  if (! deprecateWarnTriggered) {
```

2023-03-30 09:10 UTC, edleeks87 commented on src/components/show-edit-pod/show-edit-pod.component.js
> +    deprecateInputRefWarnTriggered = true;
```suggestion
    deprecateWarnTriggered = true;
```

2023-03-30 15:47 UTC, edleeks87 approved these changes
LGTM, before we merge we'll need to squash this into one commit

2023-03-30 15:48 UTC, edleeks87 submitted a review, later dismissed

2023-03-31 11:29 UTC, DlgSHi approved these changes

2023-04-03 08:41 UTC, DlgSHi approved these changes

2023-04-03 09:39 UTC, edleeks87 approved these changes

2023-04-03 09:39 UTC, merged