test(multi-action-button): add accessibility tests
Sage/carbon pull request #5918
Opened 2023-03-14 09:43 UTC by ZhuoyuJin

### Proposed behaviour
- Add `accessibility` Cypress tests for the `Multi-action-button` component to use the new cypress-component-react framework for testing.

### Current behaviour
Old approach for accessibility tests

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ] Run `npx cypress open --component` to check if there are newly added tests
- [ ] Check if the `multi-action-button.test.js` file passed
- [ ] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [ ] Run `npx cypress run --e2e` to check none of the feature files have regressed
- [ ] Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that `Multi-action-button` tests are not running twice.

2023-03-15 10:03 UTC, DlgSHi requested changes

2023-03-15 10:03 UTC, DlgSHi commented on src/components/multi-action-button/multi-action-button-test.stories.tsx
> +
can you add `includeStories` parameter to include only `default` story, please?

2023-03-15 13:51 UTC, stephenogorman commented on src/components/multi-action-button/multi-action-button.test.js
> +    });
You could add an accessibility test for the MultiActionNestedInDialog const.

2023-03-15 13:58 UTC, DlgSHi approved these changes

2023-03-20 10:44 UTC, stephenogorman submitted a review, later dismissed

2023-03-20 13:58 UTC, stephenogorman approved these changes

2023-03-20 14:21 UTC, DlgSHi requested changes
1. We need to expand the hidden container to make an `axe` tests for `MultiActionButton` and not the `Accordion`
2. We should add one test to check expanded `MultiActionButton` with all buttons visible / rendered

2023-03-24 10:43 UTC, merged

2023-03-24 13:27 UTC, carbonci commented
:tada: This PR is included in version 116.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/116.2.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v116.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: