feat(help): improve accessibility
Sage/carbon pull request #5931
Opened 2023-03-21 15:31 UTC by robinzigmond

Remove `role="button"` from help icon, and remove `aria-label` and `aria-describedby`. The relevant text is now included in the DOM directly in styles that make it not visible but are picked up by screenreaders - ensuring a good experience for screenreader users. Deprecate the `tooltipId` prop which is no longer necessary for accessibility, and deprecate `aria-label` and replace with `accessibilityLabel` (as the prop's value is no longer used for an `aria-label` attribute)

fix #5569

### Proposed behaviour

The help icon, which is not clickable and merely displays a tooltip on focus/hover, should not be announced as a button. There should be no Axe violations, and screenreaders should read both the supplied `ariaLabel` prop if supplied (otherwise it defaults to "help") and the tooltip text.

Further `ariaLabel` should be renamed (I have chosen `accessibilityLabel` but am open to better suggestions) because the prop is no longer used as an HTML `aria-label` attribute.

### Current behaviour

Help icon is announced as a button by screenreaders, which is incorrect and confusing.

### Checklist

- [X] Commits follow our style guide
- [X] Related issues linked in commit messages if required
- [X] Screenshots are included in the PR if useful
- [X] All themes are supported if required
- [X] Unit tests added or updated if required
- [X] Cypress automation tests added or updated if required
- [X] Storybook added or updated if required
- [X] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [X] Typescript `d.ts` file added or updated if required
- [X] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

Do both general regression testing and screenreader testing (both Voiceover with Safari on MacOS and NVDA with supported browsers on Windows) on the Help component and all other components which use it: Heading and the various input components

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

2023-03-24 17:24 UTC, grabkowski requested changes
I think that this change will not improve accessibility and will break the ARIA tooltip pattern.
I don't know why would the button role of the tooltip trigger be wrong, almost every component library is using buttons for this purpose.

We should consult that with Accessibility Team before we do implement that change.

2023-03-27 13:53 UTC, robinzigmond commented
> I think that this change will not improve accessibility and will break the ARIA tooltip pattern. I don't know why would the button role of the tooltip trigger be wrong, almost every component library is using buttons for this purpose.
> 
> We should consult that with Accessibility Team before we do implement that change.

Thanks Kuba for the review - for some reason I didn't spot these comments till now.

Can you give me a link to somewhere else that is using this pattern - `role="button"` on something that only works on hover, not on llick - or an article sugesting it? I'm not seeing what you think will break here?

I already discussed this with Martin with regard to what to do, and he was the one who suggested this pattern of using visibly-hidden text. (He did also suggest, as an alternative, keeping it as a button but making it work on click rather than hover - but when I discussed the options with Nick we agreed the visibly hidden text would be easier and wouldn't result in any changes for users without accessibility needs, so it seemed the best change to make.)

2023-03-29 14:05 UTC, grabkowski submitted a review, later dismissed

2023-03-30 14:48 UTC, grabkowski approved these changes

2023-04-04 15:36 UTC, Parsium submitted a review, later dismissed

2023-04-06 15:47 UTC, Parsium approved these changes

2023-04-13 09:37 UTC, tomdavies73 approved these changes

2023-04-26 14:48 UTC, closed without merging