test(navigation-bar): add accessibility tests
Sage/carbon pull request #5944
Opened 2023-03-28 15:22 UTC by ZhuoyuJin

### Proposed behaviour

- Add `accessibility` Cypress tests for the `Navigation-bar` component to use the new cypress-component-react framework for testing.

### Current behaviour
Old approach for accessibility tests

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ] Run `npx cypress open --component` to check if there is newly added test.file
- [ ] Check if the `navigation-bar.test.js` file passed
- [ ] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [ ] Run `npx cypress run --e2e` to check none of the feature files have regressed
- [ ] Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that `Navigation-bar` tests are not running twice.

2023-03-29 10:25 UTC, stephenogorman requested changes

2023-03-29 10:25 UTC, stephenogorman commented on src/components/navigation-bar/navigation-bar.test.js
> +    it("should pass accessibilty tests for NavigationBar Default story", () => {
'accessibility' is misspelled as 'accessibilty' on each test.

2023-03-30 08:54 UTC, stephenogorman submitted a review, later dismissed

2023-03-31 09:12 UTC, stephenogorman approved these changes

2023-03-31 10:28 UTC, DlgSHi approved these changes

2023-03-31 15:25 UTC, merged

2023-04-03 15:00 UTC, carbonci commented
:tada: This PR is included in version 117.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/117.2.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v117.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: