test(alert): typescript refatctor
Sage/carbon pull request #6019
Opened 2023-05-11 13:29 UTC by ZhuoyuJin

### Proposed behaviour

Rename the `componentName.test.js` into `componentName.test.tsx` file in `./cypress/components/componentName/` folder
Refactor tests to Typescript
Move any remaining stories in `componentName.test.tsx` file to `componentName-test.stories.tsx` in './src/components/componentName/' folder.

### Current behaviour

tests are in js not ts

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions
- [ ] Run `npx cypress open --component` to check if the`alert.cy.tsx` file passed
- [ ] Run `npx cypress run --component` to check none of the other *.cy.tsx files have regressed
- [ ] Run `npx cypress run --e2e` to check none of the feature files have regressed
- [ ] Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that `alert` tests are not running twice.

2023-05-12 09:06 UTC, DlgSHi requested changes

2023-05-12 09:06 UTC, DlgSHi commented on cypress/components/alert/alert.cy.tsx
> +      // https://github.com/bahmutov/cypress-each/issues/2
no, you need to wrap `[SIZE.EXTRALARGE as string, 1080],` and don't ignore it

2023-05-15 08:46 UTC, DlgSHi submitted a review, later dismissed

2023-05-15 09:51 UTC, divyajindel approved these changes

2023-05-16 16:27 UTC, Parsium commented on cypress/components/alert/alert.cy.tsx
>      ])(
This should help with simplifying the type declaration a little bit, by instead writing the input as an array containing `[string, number]` tuples: 

```tsx
it.each([
      [SIZE.EXTRASMALL, 300],
      [SIZE.SMALL, 380],
      [SIZE.MEDIUMSMALL, 540],
      [SIZE.MEDIUM, 750],
      [SIZE.MEDIUMLARGE, 850],
      [SIZE.LARGE, 960],
      [SIZE.EXTRALARGE, 1080],
    ] as [string, number][])(
```

2023-05-16 16:30 UTC, Parsium approved these changes

2023-05-16 16:30 UTC, Parsium commented on cypress/components/alert/alert.cy.tsx
>      it.each([
This should help with simplifying the type declaration a little bit, by instead writing the input as an array containing `[string, number]` tuples: 

```tsx
it.each([
      [SIZE.EXTRASMALL, 300],
      [SIZE.SMALL, 380],
      [SIZE.MEDIUMSMALL, 540],
      [SIZE.MEDIUM, 750],
      [SIZE.MEDIUMLARGE, 850],
      [SIZE.LARGE, 960],
      [SIZE.EXTRALARGE, 1080],
    ] as [string, number][])(
```

2023-05-16 16:30 UTC, Parsium commented on cypress/components/alert/alert.cy.tsx
> +          // eslint-disable-next-line no-unused-expressions, jest/valid-expect
We should be ok to disable the jest linting rules here. Ideally, eslint shouldn't be linting the cypress tests with jest rules, so we will need to address this for you as part of FE-5758.

2023-05-17 10:02 UTC, Parsium submitted a review, later dismissed

2023-05-18 11:49 UTC, divyajindel commented
@ZhuoyuJin  could you please add these below lines top of the alert.cy.tsx file please and remove eslint comment from other places.

/* eslint-disable jest/valid-expect */
/* eslint-disable no-unused-expressions */

2023-05-18 12:08 UTC, Parsium commented
> @ZhuoyuJin could you please add these below lines top of the alert.cy.tsx file please and remove eslint comment from other places.
>
> /* eslint-disable jest/valid-expect _/ /_ eslint-disable no-unused-expressions */

I think going forward with the typescript test conversions, disabling the jest eslint rules for the whole file would be good to avoid having to keep disabling line by line - just until we have sorted out the eslint config so the jest rules are not applied to the cypress tests.

However, for non-jest related rules, I would wary of disabling them for the whole test file, since this would mean we are not adhering to the code practices we have set out as a team.

2023-05-18 14:07 UTC, divyajindel approved these changes

2023-05-18 14:20 UTC, DlgSHi commented on cypress/components/alert/alert.cy.tsx
> +    ] as [string, number][])(
why as `string` and not `AlertProps["size"]`?

2023-05-18 14:34 UTC, DlgSHi approved these changes

2023-05-18 15:28 UTC, merged