test(accordion): typescript refactor
Sage/carbon pull request #6026
Opened 2023-05-12 09:39 UTC by stephenogorman

### Proposed behaviour

- Rename the `accordion.cy.js` to `accordion.cy.tsx` file in `./cypress/components/accordion/` folder.
- Refactor tests to Typescript.  

### Current behaviour

Tests are in js not ts

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions
- [ ] Run `npx cypress open --component` to check if the`alert.cy.tsx` file passed
- [ ] Run `npx cypress run --component` to check none of the other *.cy.tsx files have regressed
- [ ] Run `npx cypress run --e2e` to check none of the feature files have regressed
- [ ] Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that `accordion` tests are not running twice.

2023-05-12 10:42 UTC, DlgSHi requested changes

2023-05-12 10:42 UTC, DlgSHi commented on cypress/components/accordion/accordion.cy.tsx
> +    it.each([["700px"], ["900px"], ["1100px"], ["1300px"]])(
```suggestion
    it.each(["700px", "900px", "1100px", "1300px"])(
```

2023-05-15 06:07 UTC, DlgSHi approved these changes

2023-05-16 10:26 UTC, edleeks87 approved these changes

2023-05-16 11:21 UTC, merged

2023-05-16 13:07 UTC, carbonci commented
:tada: This PR is included in version 118.3.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/118.3.2)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v118.3.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: