test(heading): typescript refactor
Sage/carbon pull request #6036
Opened 2023-05-17 13:59 UTC by divyajindel

### Proposed behaviour
- Rename the `heading.cy.js` to `heading.cy.tsx` file in `./cypress/components/badge/` folder.
- Refactor tests to Typescript.  

### Current behaviour

Currently Badge component is in JS not in TS.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions
- [x] Run `npx cypress open --component` to check if the`heading.cy.tsx` file passed
- [x] Run `npx cypress run --component` to check none of the other *.cy.tsx files have regressed

2023-05-18 13:38 UTC, DlgSHi requested changes

2023-05-18 13:38 UTC, DlgSHi commented on cypress/components/heading/heading.cy.tsx
> +        "h1" as const,
shall we make this `as HeadingProps["headingType"]` ?

2023-05-22 05:48 UTC, DlgSHi requested changes
Also, we need to mention in PR description about the `badge` commit

2023-05-22 05:48 UTC, DlgSHi commented on cypress/components/heading/heading.cy.tsx
> +      it.each(["h1", "h2", "h3", "h4", "h5"] as Exclude<
```suggestion
      it.each(["h1", "h2", "h3", "h4", "h5"] as HeadingProps["headingType"][]
```

2023-05-22 05:48 UTC, DlgSHi commented on cypress/components/heading/heading.cy.tsx
> +        HeadingProps["headingType"],
```suggestion
```

2023-05-22 05:48 UTC, DlgSHi commented on cypress/components/heading/heading.cy.tsx
> +        undefined
```suggestion
```

2023-05-22 05:48 UTC, DlgSHi commented on cypress/components/heading/heading.cy.tsx
> +      >[])(
```suggestion
```

2023-05-22 12:01 UTC, Parsium reviewed
Looks good to me @divyajindel 👍🏼 Please could you add those changes to `badge.cy.tsx` as a separate commit? That way it makes it a bit clearer that the changes are separate to refactoring the `Heading` tests

2023-05-22 14:16 UTC, Parsium submitted a review, later dismissed

2023-05-22 14:50 UTC, Parsium approved these changes

2023-05-22 14:57 UTC, DlgSHi approved these changes

2023-05-22 15:30 UTC, ZhuoyuJin approved these changes

2023-05-22 16:20 UTC, merged

2023-05-23 09:47 UTC, carbonci commented
:tada: This PR is included in version 118.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/118.4.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v118.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: