test(typography): refactor to TS
Sage/carbon pull request #6121
Opened 2023-06-15 08:53 UTC by DlgSHi

### Proposed behaviour

- Rename the `typography.cy.js` to the `typography.cy.tsx` file in `./cypress/components/typography/` folder.
- Refactor tests to Typescript.  

### Current behaviour

Typography tests are in js not ts.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions
- [ ] Run `npx cypress open --component` to check if the `typography.cy.tsx` file passed
- [ ] Run `npx cypress run --component` to check none of the other `*.cy.tsx` files have regressed

2023-06-15 15:17 UTC, sianford approved these changes

2023-06-15 15:44 UTC, DipperTheDan requested changes

2023-06-15 15:44 UTC, DipperTheDan commented on cypress/components/numeral-date/numeral-date.cy.tsx
Issue: If you're refactoring `Numeral Date` and `Typography` in one PR, you'll need to split them off in to separate commits.  
`test(numeral-date):...`
`test(typography):...`

2023-06-16 08:10 UTC, DipperTheDan approved these changes

2023-06-16 08:56 UTC, stephenogorman approved these changes

2023-06-16 09:24 UTC, merged