test(navigation-bar): refactor ts
Sage/carbon pull request #6139
Opened 2023-06-20 19:07 UTC by ZhuoyuJin

### Proposed behaviour

- Rename the `navigation-bar.cy.js` to the `navigation-bar.cy.tsx` file in `./cypress/components/navigation-bar/` folder.
- Refactor tests to Typescript.  
- Add the hr-test.stories.tsx to ./src/components/hr/ folder

### Current behaviour

Navigation-bar tests are in js not ts.
Navigation-bar-test.stories.tsx does not exist

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions
- [ ] Run `npx cypress open --component` to check if the `navigation-bar.cy.tsx` file passed
- [ ] Run `npx cypress run --component` to check none of the other `*.cy.tsx` files have regressed

2023-06-21 07:41 UTC, DlgSHi requested changes

2023-06-21 07:41 UTC, DlgSHi commented on src/components/navigation-bar/navigation-bar-test.stories.tsx
> +  children: undefined,
```suggestion
  children: "Example content",
```

2023-06-22 08:46 UTC, DlgSHi submitted a review, later dismissed

2023-06-22 10:36 UTC, stephenogorman submitted a review, later dismissed

2023-06-22 15:16 UTC, DipperTheDan commented on src/components/navigation-bar/navigation-bar-test.stories.tsx
> +  const isChildren = children != null ? children : "Cypress tests";
```suggestion
  const isChildren = children !== null ? children : "Cypress tests";
```

2023-06-23 08:41 UTC, DlgSHi approved these changes

2023-06-23 08:59 UTC, DipperTheDan approved these changes

2023-06-23 09:55 UTC, merged

2023-06-29 10:12 UTC, carbonci commented
:tada: This PR is included in version 119.3.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/119.3.3)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v119.3.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: