test(dialog): typescript refactor
Sage/carbon pull request #6150
Opened 2023-06-26 10:00 UTC by divyajindel

### Proposed behaviour

- Rename the `dialog.cy.js` file to `dialog.cy.tsx` file in `./cypress/components/dialog/` folder.
- Refactor tests to Typescript.

### Current behaviour

Dialog tests are in js not ts.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

- [ ] Run npx cypress open --component to check if the `dialog.cy.tsx` file passed
- [ ] Run npx cypress run --component --browser chrome to check none of the other `*.cy.tsx` files have regressed

2023-06-26 13:12 UTC, DlgSHi requested changes

2023-06-26 13:12 UTC, DlgSHi commented on cypress/components/dialog/dialog.cy.tsx
> +      closeIconButton().click().as("waitForClick");
we don't use this

we can do:
`cy.wait("@waitForClick")`

and only then this will be a case of using an alias

2023-06-26 14:24 UTC, divyajindel commented on cypress/components/dialog/dialog.cy.tsx
There were some duplicate tests for accessibility so I've deleted all the duplicate code. Regarding your second point I'll have a look.

2023-06-28 13:24 UTC, sianford commented on cypress/components/dialog/dialog.cy.tsx
> +  it("should pass accessibility tests for Dialog Editable story", () => {
I think this test case should be within the brackets of the other accessibility tests `Describe...`. It's out on its own here.

2023-06-28 13:25 UTC, sianford commented on cypress/components/dialog/dialog.cy.tsx
> +  it("should pass accessibility tests for Dialog FocusingADifferentFirstElement story", () => {
As above, I think this test case should be within the brackets of the other accessibility tests `Describe...`. It's out on its own here.

2023-06-28 13:25 UTC, sianford commented on cypress/components/dialog/dialog.cy.tsx
> +  it("should pass accessibility tests for Dialog OverridingContentPadding story", () => {
As above, I think this test case should be within the brackets of the other accessibility tests `Describe...`. It's out on its own here.

2023-06-28 13:26 UTC, sianford commented on cypress/components/dialog/dialog.cy.tsx
> +  it("should pass accessibility tests for Dialog OtherFocusableContainers story", () => {
As above, I think this test case should be within the brackets of the other accessibility tests `Describe...`. It's out on its own here.

2023-06-28 13:26 UTC, sianford commented on cypress/components/dialog/dialog.cy.tsx
> +  it("should pass accessibility tests for Dialog Responsive story", () => {
As above, I think this test case should be within the brackets of the other accessibility tests `Describe...`. It's out on its own here.

2023-06-28 13:27 UTC, sianford commented on cypress/components/dialog/dialog.cy.tsx
>    it("should have the expected border radius styling", () => {
I think this test case should be within the brackets of the other props tests `Describe...`. It's out on its own here.

2023-06-28 14:53 UTC, sianford submitted a review, later dismissed

2023-06-29 07:04 UTC, DlgSHi approved these changes

2023-06-29 10:13 UTC, robinzigmond commented on cypress/components/dialog/dialog.cy.tsx
> +    it.each(["top", "topRight", "right"] as ("top" | "topRight" | "right")[])(
```suggestion
    it.each(["top", "topRight", "right"] as Cypress.PositionType[])(
```

**suggestion**: This seems to work and avoids the repetition of the values. This is a type defined within Cypress, for the arguments that can be given to `.click`.

2023-06-29 13:31 UTC, robinzigmond approved these changes

2023-06-29 13:33 UTC, sianford approved these changes

2023-06-29 13:39 UTC, DlgSHi approved these changes

2023-06-29 14:47 UTC, merged

2023-07-03 12:09 UTC, carbonci commented
:tada: This PR is included in version 119.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/119.4.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v119.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: