test(select): typescript refactor
Sage/carbon pull request #6169
Opened 2023-06-30 14:32 UTC by stephenogorman

### Proposed behaviour

- Rename the `select.cy.js` to `select.cy.tsx` file in `./cypress/components/select/` folder.
- Refactor tests to Typescript.  

### Current behaviour

`Select` tests are in js not ts.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions
- [ ] Run `npx cypress open --component` to check if the `select.cy.tsx` file passed
- [ ] Run `npx cypress run --component` to check none of the other `*.cy.tsx` files have regressed

2023-07-03 11:01 UTC, DlgSHi requested changes

2023-07-03 11:01 UTC, DlgSHi commented on cypress/components/select/simple-select/simple-select.cy.tsx
> +import { SimpleSelectProps } from "components/select";
same here for `path`

2023-07-03 13:32 UTC, stephenogorman commented on cypress/components/select/filterable-select/filterable-select.cy.tsx
> -        if (position === "auto") {
A couple of reasons:
1. As position was set by the parameters to either 'top', 'bottom', 'left' or 'right', this condition was never tested.
2. the listPlacement prop as 'Side' which only accepts 'top', 'bottom', 'left' or 'right', so 'auto' was being flagged by typescript.

2023-07-04 06:57 UTC, DlgSHi reviewed
looks good to me, squash the commits only :)

2023-07-06 08:01 UTC, DlgSHi approved these changes

2023-07-06 09:57 UTC, edleeks87 approved these changes

2023-07-06 10:32 UTC, divyajindel approved these changes

2023-07-06 12:23 UTC, merged

2023-07-06 13:39 UTC, carbonci commented
:tada: This PR is included in version 119.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/119.6.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v119.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: