test(dialog-full-screen): refactor ts
Sage/carbon pull request #6200
Opened 2023-07-14 09:33 UTC by ZhuoyuJin

### Proposed behaviour

- Rename the `dialog-full-screen.cy.js` to `tile.cy.tsx` file in `./cypress/components/dialog-full-screen/` folder.
- Refactor tests to Typescript.  

### Current behaviour

`Dialog-full-screen` tests are in js not ts.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions
- [x] Run `npx cypress open --component` to check if the `dialog-full-screen.cy.tsx` file passed
- [x] Run `npx cypress run --component` to check none of the other `*.cy.tsx` files have regressed

2023-07-17 11:26 UTC, DlgSHi requested changes

2023-07-17 11:26 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      closeIconButton().should("be.disabled").and("have.attr", "disabled");
we suppose to add that if we press/trigger this button the `DialogFullScreen` should remain opened

2023-07-17 11:26 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      return buttonDataComponent()
could we avoid using this `return` here?

2023-07-17 11:26 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      return buttonDataComponent()
same here

2023-07-17 11:26 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      return buttonDataComponent()
return

2023-07-17 11:26 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      return buttonDataComponent()
return

2023-07-17 11:26 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      return buttonDataComponent()
same here

2023-07-17 11:26 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      return buttonDataComponent()
same here

2023-07-17 11:26 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      return buttonDataComponent()
same here

2023-07-17 11:26 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      return buttonDataComponent()
same here

2023-07-17 11:26 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      return buttonDataComponent()
same here

2023-07-19 09:26 UTC, stephenogorman submitted a review, later dismissed

2023-07-20 07:12 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +import { DialogFullScreenProps } from "components/dialog-full-screen";
could you update the path?

2023-07-20 07:12 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      cy.checkAccessibility();
shall we add something to be sure that Dialog is opened? Like the crossIcon is visible, or something similar?

2023-07-20 07:12 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      buttonDataComponent().contains("Open DialogFullScreen").click();
shall we add something to be sure that Dialog is opened? Like the crossIcon is visible, or something similar?

2023-07-20 07:12 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      buttonDataComponent().contains("Open DialogFullScreen").click();
shall we add something to be sure that Dialog is opened? Like the crossIcon is visible, or something similar?

2023-07-20 07:12 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      buttonDataComponent().contains("Open DialogFullScreen").click();
shall we add something to be sure that Dialog is opened? Like the crossIcon is visible, or something similar?

2023-07-20 07:12 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      buttonDataComponent().contains("Open DialogFullScreen").click();
shall we add something to be sure that Dialog is opened? Like the crossIcon is visible, or something similar?

2023-07-20 07:12 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      buttonDataComponent().contains("Open DialogFullScreen").click();
and here

2023-07-20 07:12 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      buttonDataComponent().contains("Open DialogFullScreen").click();
same here

2023-07-20 07:12 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      buttonDataComponent().contains("Open Demo using autoFocus").click();
same here

2023-07-20 07:12 UTC, DlgSHi commented on cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
> +      buttonDataComponent().contains("Open DialogFullScreen").click();
and here

2023-07-21 11:50 UTC, tomdavies73 approved these changes

2023-07-21 15:44 UTC, merged

2023-07-24 08:51 UTC, carbonci commented
:tada: This PR is included in version 119.6.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/119.6.3)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v119.6.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: