feat(option-group-header, option-row, option): allow custom IDs to be…
Sage/carbon pull request #6201
Opened 2023-07-14 14:36 UTC by tomdavies73

fix #6126

### Proposed behaviour

A condition has been added to `SelectList` which checks if the `id` prop is present on any children, if it is the GUID is not applied. This provides consumers with flexibility to pass specific IDs to `OptionGroupHeader`, `OptionHeader`, and `Option` component children.

### Current behaviour

Currently, a GUID is applied to every potential child of the `SelectList` component `(OptionGroupHeader, OptionRow, Option)`. Even when consumers pass the `id` prop, the id attribute is still overwritten with a GUID.

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

2023-07-20 13:34 UTC, DipperTheDan commented on src/components/select/select-list/select-list.component.tsx
> +        // React.Children.map(children, () => guid()) ||
**issue:** Left some commented out code in.

2023-07-20 13:47 UTC, Parsium reviewed
Happy to approve once the comment from @DipperTheDan has been addressed 👍🏼

2023-07-20 14:08 UTC, Parsium approved these changes

2023-07-20 14:38 UTC, DipperTheDan approved these changes

2023-08-01 14:58 UTC, sianford submitted a review, later dismissed
Tested in codesandbox and Storybook. No issues found.

2023-08-01 14:59 UTC, DlgSHi commented on cypress/components/select/filterable-select/filterable-select.cy.tsx
> +      const option = "Amber";
can we move this to a consts at the top of the file? and then use it below

2023-08-01 14:59 UTC, DlgSHi commented on cypress/components/select/multi-select/multi-select.cy.tsx
> +      const option = "Amber";
same here

2023-08-01 15:10 UTC, stephenogorman requested changes

2023-08-02 05:58 UTC, DlgSHi approved these changes

2023-08-02 07:47 UTC, DipperTheDan approved these changes

2023-08-02 08:54 UTC, merged