test(flat-table): typescript refactor
Sage/carbon pull request #6207
Opened 2023-07-18 16:30 UTC by stephenogorman

### Proposed behaviour

- Rename the `flat-table.cy.js` to `flat-table.cy.tsx` file in `./cypress/components/flat-table/` folder.
- Refactor tests to Typescript.  

### Current behaviour

`Flat-table` tests are in js not ts.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions
- [ ] Run `npx cypress open --component` to check if the `dialog-full-screen.cy.tsx` file passed
- [ ] Run `npx cypress run --component` to check none of the other `*.cy.tsx` files have regressed

2023-07-20 06:38 UTC, DlgSHi requested changes

2023-07-20 06:38 UTC, DlgSHi commented on cypress/components/flat-table/flat-table.cy.tsx
> +} from "components/flat-table";
could you update the path to be like below?

2023-07-20 06:38 UTC, DlgSHi commented on cypress/components/flat-table/flat-table.cy.tsx
> +    it.each([["visible"], ["hidden"], ["clip"], ["scroll"], ["auto"]])(
```suggestion
    it.each(["visible", "hidden", "clip", "scroll", "auto"])(
```

2023-07-20 06:38 UTC, DlgSHi commented on cypress/components/flat-table/flat-table.cy.tsx
> +      CypressMountWithProviders(
why we can't move this component to `flat-table-test.stories.tsx` file?

2023-07-20 06:38 UTC, DlgSHi commented on cypress/components/flat-table/flat-table.cy.tsx
> +      CypressMountWithProviders(
same question here

2023-07-20 06:38 UTC, DlgSHi commented on cypress/components/flat-table/flat-table.cy.tsx
> +      CypressMountWithProviders(
and here

2023-07-20 06:38 UTC, DlgSHi commented on src/components/flat-table/flat-table-test.stories.tsx
> +export const FlatTableComponent = ({ ...props }) => {
```suggestion
export const FlatTableComponent = (props: FlatTableProps) => {
```

2023-07-20 06:38 UTC, DlgSHi commented on src/components/flat-table/flat-table-test.stories.tsx
> +export const FlatTableFooterComponent = ({ ...props }) => {
typing for `props`

2023-07-20 06:38 UTC, DlgSHi commented on src/components/flat-table/flat-table-test.stories.tsx
> +  props: Partial<FlatTableCheckboxProps> & Partial<FlatTableCheckboxProps>
same props passed

```suggestion
  props: Partial<FlatTableCheckboxProps>
```

2023-07-20 09:16 UTC, divyajindel commented on cypress/components/flat-table/flat-table.cy.tsx
> +/* eslint-disable jest/no-disabled-tests */
Could you please remove this line ?

2023-07-20 09:18 UTC, divyajindel requested changes

2023-07-20 09:18 UTC, divyajindel commented on cypress/components/flat-table/flat-table.cy.tsx
> +/* eslint-disable jest/no-disabled-tests */
Could you please remove this line ?

2023-07-20 09:22 UTC, divyajindel requested changes

2023-07-20 09:22 UTC, divyajindel commented on src/components/flat-table/flat-table-test.stories.tsx
> +  props: Partial<FlatTableProps> & Partial<FlatTableCellProps>
```suggestion
 props: Partial<FlatTableProps> & FlatTableCellProps
```

2023-07-20 14:05 UTC, divyajindel approved these changes

2023-07-20 14:23 UTC, DipperTheDan commented on cypress/components/flat-table/flat-table.cy.tsx
> +        if (i === 0 || i === 1 || i === 3) {
**suggestion:** could do the inverse here and say: 
```suggestion
        if (i !== 2 || i !== 4) {
```
uses less parameters in the `if` condition. I'm happy either way though and it's fine this way if this is how you lot in QA want the tests to be written.

2023-07-21 08:21 UTC, DipperTheDan approved these changes

2023-07-21 09:26 UTC, DlgSHi approved these changes

2023-07-21 14:24 UTC, divyajindel approved these changes

2023-07-21 14:40 UTC, merged

2023-07-24 08:51 UTC, carbonci commented
:tada: This PR is included in version 119.6.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/119.6.3)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v119.6.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: