test(content): playwright refactor
Sage/carbon pull request #6260
Opened 2023-08-16 15:39 UTC by divyajindel

### Proposed behaviour

- Copy `content` folder from `/cypress/locators/` to `/playwright/components/`
- Rename `index.js` to `index.ts` and `locators.js` to `locators.ts` in `/playwright/components/content/` folder
- Refactor `index.ts` to Playwright
- Copy `content.cy.tsx from `/cypress/components/content/` to `/src/components/content/`
- Rename `content.cy.tsx` to `content.pw.tsx` in `/src/components/content/` folder
- Refactor tests to Playwright

### Current behaviour

`Content` tests are in Cypress not Playwright.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions
- [x] Run Content tests in Playwright Test Runner to check if the `content.pw.tsx` file passed
- [x] Run all other tests in Playwright Test Runner to check none of the other `*.pw.tsx` files have regressed

2023-08-17 11:59 UTC, stephenogorman requested changes

2023-08-17 11:59 UTC, stephenogorman commented on src/components/content/content.pw.tsx
> +    test(`should check ${variant} as variant for Content components ${titleColor}`, async ({
I don't think ${titleColor} is necessary in this test title.

2023-08-17 11:59 UTC, stephenogorman commented on src/components/content/content.pw.tsx
> +      await expect(contentElement).toHaveCSS("text-align", `${alignment}`);
I don't think you need to enclose the alignment variable in quotes, the following should work:
`await expect(contentElement).toHaveCSS("text-align", alignment);`

2023-08-17 11:59 UTC, stephenogorman commented on src/components/content/content.pw.tsx
> +  );
The refactor to Playwright has been done correctly for this test, but I think the original Cypress test is testing the wrong thing. It's supposed to be verifying that the `bodyFullWidth` prop sets the content body width to its maximum, but is actually testing the same thing as the previous test (content Title). The following actually tests the bodyFullWidth prop:

```
  ([
    [true, 70, totalWidth],
    [false, 50, totalWidth],
  ] as [boolean, number, number][]).forEach(
    ([bodyFullWidth, titleWidth]) => {
      test(`should check Content component has bodyFullWidth as ${bodyFullWidth}`, async ({
        mount,
        page,
      }) => {
        await mount(
          <ContentComponent
            bodyFullWidth={bodyFullWidth}
            titleWidth={titleWidth}
          />
        );
        const cssWidth = await getStyle(contentBody(page), "width");
        if (bodyFullWidth === true) {
          await expect(parseInt(cssWidth)).toEqual(totalWidth);
        } else {
          await expect(parseInt(cssWidth)).not.toEqual(totalWidth);
        }
      });
    }
  );
```

2023-08-18 08:53 UTC, stephenogorman submitted a review, later dismissed

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content-test.stories.tsx
> -export const ContentComponentTest = ({
**suggestion**: You can add this back, there's not much reason for it to be deleted. Keeping the test story means people can still use it to test locally.

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content.pw.tsx
> +      const contentElement = contentTitle(page);
**suggestion**: the `contentElement`, `const` doesn't need to be declared here. You can just include the `contentTitle` locator within the `expect` underneath, reducing a line of code like so `await expect(contentTitle(page)).toHaveCSS("color", `${titleColor}`);`

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content.pw.tsx
> +      await expect(await contentBody(page)).toHaveText(children);
**issue**: there is an unnecessary `await` within this expression

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content.pw.tsx
> +      await expect(await contentBody(page)).toHaveText(children);
**suggestion**: just use one await before the `expect` like this `await expect(contentBody(page)).toHaveText(children);`

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content.pw.tsx
> +      await expect(await contentTitle(page)).toHaveText(title);
**issue:** same comment as above, another unnecessary `await`

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content.pw.tsx
> +      await expect(parseInt(cssWidth)).toBeLessThanOrEqual(computedWidth - 30);
**issue**: unnecessary `await` x2

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content.pw.tsx
> +      await expect(parseInt(cssWidth)).toBeLessThanOrEqual(computedWidth - 30);
**suggestion**: remove the unnecessary awaits, like so `expect(parseInt(cssWidth)).toBeLessThanOrEqual(computedWidth - 30) expect(parseInt(cssWidth)).toBeGreaterThanOrEqual(computedWidth - 31 );`

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content.pw.tsx
> +        await expect(parseInt(cssWidth)).toEqual(totalWidth);
**issue**: unnecessary `await` x 2

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content.pw.tsx
> +        await expect(parseInt(cssWidth)).toEqual(totalWidth);
**suggestion**: remove the unnecessary awaits like so ` expect(parseInt(cssWidth)).toEqual(totalWidth);
      } else {
         expect(parseInt(cssWidth)).not.toEqual(totalWidth);
      }`

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content.pw.tsx
> +      await expect(await contentBody(page)).toHaveText(children);
VS Code will let you know if an `await` is unnecessary by putting three dots underneath the `await` in question like so 
![Screenshot 2023-08-18 at 12 48 20](https://github.com/Sage/carbon/assets/114918852/4c3c7d47-be27-4eed-ac02-f258febd2e3b)
![Screenshot 2023-08-18 at 12 48 33](https://github.com/Sage/carbon/assets/114918852/655cfa44-908a-4479-bb51-03c33b0aa62f)

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content.pw.tsx
> +    const contentElement = contentTitle(page);
**suggestion**: the `contentElement` `const` does not need to be defined here, you can just add the `contentTitle` locator within the `expect`. Similar comment to above

2023-08-18 11:56 UTC, tomdavies73 commented on src/components/content/content.pw.tsx
> +      const contentElement = contentTitle(page);
**suggestion**: the `contentElement` `const` does not need to be defined here, you can just add the `contentTitle` locator within the `expect`. Similar comment to above

2023-08-18 15:40 UTC, tomdavies73 approved these changes

2023-08-21 15:41 UTC, ZhuoyuJin approved these changes

2023-08-22 08:48 UTC, merged

2023-08-22 09:13 UTC, carbonci commented
:tada: This PR is included in version 119.12.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/119.12.1)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v119.12.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: