test(message): migrate cypress tests to playwright
Sage/carbon pull request #6270
Opened 2023-08-24 14:18 UTC by divyajindel

### Proposed behaviour

- Copy `message` folder from `/cypress/locators/` to `/playwright/components/`
- Rename `index.js` to `index.ts` and `locators.js` to `locators.ts` in `/playwright/components/message/` folder
- Refactor `index.ts` to Playwright
- Copy `message.cy.tsx from `/cypress/components/message/` to `/src/components/message/`
- Rename `message.cy.tsx` to `message.pw.tsx` in `/src/components/message/` folder
- Refactor tests to Playwright

### Current behaviour

`Message` tests are in Cypress not Playwright.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions
- [x] Run message tests in Playwright Test Runner to check if the `message.pw.tsx` file passed
- [x] Run all other tests in Playwright Test Runner to check none of the other `*.pw.tsx` files have regressed

2023-08-25 15:21 UTC, DipperTheDan commented on src/components/message/message.pw.tsx
> +    test(`should check ${boolVal} for transparent background for Message component`, async ({
**suggestion:** this test description doesn't quite make sense to me when it's read out with the values. Something along the lines of:

```suggestion
    test(`should apply correct styling when transparent is ${boolVal}`, async ({
```

2023-08-29 15:10 UTC, DipperTheDan submitted a review, later dismissed

2023-08-31 09:46 UTC, ZhuoyuJin requested changes

2023-08-31 09:46 UTC, ZhuoyuJin commented on src/components/message/message.pw.tsx
> +        await expect(messagePreview(page).getAttribute("disabled")).toBeTruthy;
suggest change "await expect(messagePreview(page)).not.toBeVisible();"

2023-08-31 09:46 UTC, ZhuoyuJin commented on src/components/message/message.pw.tsx
> +        await expect(messageDismissIcon(page).getAttribute("disabled"))
Same suggestion as above, as the discussion about ".toBeTruthy" function is a bit flaky, would you be able to change it to ".not.toBeVisible();"

2023-08-31 09:46 UTC, ZhuoyuJin commented on src/components/message/message.pw.tsx
> +  (["info", "error", "success", "warning"] as any[]).forEach((variant) => {
type "any" can be replaced by the proper type for ["info", "error", "success", "warning"], which is MessageProps["variant"]

2023-08-31 09:46 UTC, ZhuoyuJin commented on src/components/message/message.pw.tsx
> +  ([
"background" is declared here, but it never uses in the actual test.

2023-08-31 09:46 UTC, ZhuoyuJin commented on src/components/message/message.pw.tsx
> +  ] as [boolean, number][]).forEach(([boolVal, paddingVal]) => {
same here, paddingVal is declared but never used in the actual test

2023-08-31 09:46 UTC, ZhuoyuJin commented on src/components/message/message.pw.tsx
> +});
The original test has "onDismiss" prop checked accessibility in line 250-255 in "message.cy.tsx" file, could you add it in?

2023-08-31 15:37 UTC, ZhuoyuJin approved these changes

2023-09-01 08:51 UTC, DipperTheDan approved these changes

2023-09-01 09:10 UTC, merged

2023-09-08 10:02 UTC, carbonci commented
:tada: This PR is included in version 120.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/120.2.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v120.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: