test(drawer): playwright refactor
Sage/carbon pull request #6288
Opened 2023-08-31 09:06 UTC by stephenogorman

### Proposed behaviour

Refactor Drawer tests from Cypress to Playwright

### Current behaviour

Tests are currently Cypress

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

N/A

### Testing instructions

### Testing instructions
- [ ] Run Drawer tests in Playwright Test Runner to check if the `drawer.pw.tsx` file passed
- [ ] Run all other tests in Playwright Test Runner to check none of the other `*.pw.tsx` files have regressed

2023-09-01 08:20 UTC, robinzigmond commented on src/components/drawer/drawer.pw.tsx
> +      drawer(page).locator("div").nth(0),
```suggestion
      drawer(page).locator("div").first(),
```

**suggestion** (non-blocking): `first` exists in Playwright as well as in Cypress. Doesn't really matter much but `first()` is a bit more immediately obvious what's happening.

2023-09-01 08:20 UTC, robinzigmond commented on src/components/drawer/drawer.pw.tsx
> +    await expect(drawer(page).locator("div").nth(0)).toHaveCSS(
**suggestion** (non-blocking): combining a couple of comments made on earlier tests:
1) the `.nth(0)` could be `.first()`
2) you could extract `draw(page).locator("div").first()` (or however you choose to write it) to a separate variable, to make the tests less repetitive and more descriptive.

2023-09-01 08:20 UTC, robinzigmond commented on src/components/drawer/drawer.pw.tsx
> +    await mount(<DrawerCustom title="cypress_title" />);
**nitpick** (non-blocking): again I think it's better not to use the word "cypress" in the custom title now

2023-09-01 08:20 UTC, robinzigmond commented on src/components/drawer/drawer.pw.tsx
> +    expect(await stickyFooter(page).count()).toBeGreaterThan(0);
**comment** (non-blocking): I don't think this `count` test is needed - it won't pass `toBeVisible()` below if it's not actually found in the DOM!

2023-09-01 08:20 UTC, robinzigmond commented on src/components/drawer/drawer.pw.tsx
> +  test("should render component with custom footer", async ({
**comment** (non-blocking): I admit I'm a bit confused by this test, and the changes that have happened to it from the Cypress version to your Playwright one.

The original Cypress one just asserted 2 things - that the sticky footer existed, but was not visible. As you've written it in Playwright, you're now scrolling it into view and checking that it's then visible, which the original test wasn't doing.

I think I understand what's happening, but I'd prefer to assert that the footer is *not* visible before the `scrollIntoViewIfNeeded` call, which would then leaving it (as far as I can see) testing basically the same thing(s) as before?

2023-09-01 08:20 UTC, robinzigmond commented on src/components/drawer/drawer.pw.tsx
> +      drawer(page).locator("div").locator("div").locator("div").nth(0)
**suggestion** (non-blocking): again, the result of this complex locator call could be extracted to a variable with a descriptive name

2023-09-01 08:20 UTC, robinzigmond commented on src/components/drawer/drawer.pw.tsx
> +      for (let i = 0; i < times; i++) {
**suggestion** (non-blocking): as mentioned in one of the other tests, this loop can really just be an `if`, which would also avoid the lint warning.

2023-09-01 08:20 UTC, robinzigmond commented on src/components/drawer/drawer.pw.tsx
> +        await expect(drawerSidebar(page)).toBeVisible();
**question** (non-blocking): do we need this visibility assertion? It's not there in the equivalent Cypress tests, and doesn't relate to the accessibility test.

Or is it something we need in Playwright to make sure it waits long enough for the sidebar to become visible? (I have no idea what the answer to that is.)

2023-09-01 08:20 UTC, robinzigmond commented on src/components/drawer/drawer.pw.tsx
> +      await expect(drawerSidebar(page)).toBeVisible();
**question** (non-blocking): same question here about whether the visibility assertion is actually needed or relevant to this particular test.

2023-09-05 09:36 UTC, robinzigmond submitted a review, later dismissed

2023-09-06 08:55 UTC, ZhuoyuJin requested changes

2023-09-06 08:55 UTC, ZhuoyuJin commented on src/components/drawer/components.test-pw.tsx
> +export const DrawerCustom = (props: Partial<DrawerProps>) => {
could you delete "DrawerCustom" from drawer-test.stories.tsx file please

2023-09-06 08:55 UTC, ZhuoyuJin commented on cypress/locators/drawer/index.js
> -  drawerSidebar().find("li").eq(index);
Is it necessary that we delete the index.js file?

2023-09-06 11:38 UTC, ZhuoyuJin approved these changes

2023-09-06 13:41 UTC, robinzigmond approved these changes

2023-09-06 16:09 UTC, ZhuoyuJin approved these changes

2023-09-06 16:11 UTC, robinzigmond approved these changes

2023-09-06 16:12 UTC, merged

2023-09-08 10:02 UTC, carbonci commented
:tada: This PR is included in version 120.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/120.2.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v120.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: