test(profile): add playwright tests
Sage/carbon pull request #6357
Opened 2023-10-09 21:48 UTC by divyajindel

### Proposed behaviour

- Refactor cypress tests to playwright

### Current behaviour

- Tests are currently using cypress

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

N/A

### Testing instructions

- [x] Run Icon tests in Playwright Test Runner to check if the profile.pw.tsx file passed
- [x] Run all other tests in Playwright Test Runner to check none of the other *.pw.tsx files have regressed

2023-10-10 15:06 UTC, stephenogorman requested changes

2023-10-10 15:06 UTC, stephenogorman commented on src/components/profile/profile.pw.tsx
> +      await expect(initialPreview(page)).toHaveCSS("width", "38px");
This test is supposed to check the name and initials of the Profile, but only verifies height and width.

2023-10-11 08:17 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +  test(`should pass accessibility tests for className prop`, async ({
```suggestion
  test(`should pass accessibility tests when className prop is passed`, async ({
```

2023-10-11 08:17 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +    test(`should pass accessibility tests for email prop set as ${email}`, async ({
```suggestion
    test(`should pass accessibility tests when email prop is passed as ${email}`, async ({
```

2023-10-11 08:17 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +    test(`should pass accessibility tests for name prop set as ${name}`, async ({
```suggestion
    test(`should pass accessibility tests when name prop is passed as ${name}`, async ({
```

2023-10-11 08:17 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +    test(`should pass accessibility tests for size prop set as ${size}`, async ({
```suggestion
    test(`should pass accessibility tests when size prop is passed as ${size}`, async ({
```

2023-10-11 08:17 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +    test(`should pass accessibility tests for initials when name prop is set as ${name}`, async ({
```suggestion
    test(`should pass accessibility tests when name prop is passed as ${name} and initials are acronymized`, async ({
```

2023-10-11 08:17 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +    test(`should pass accessibility tests for src prop as ${url}`, async ({
```suggestion
    test(`should pass accessibility tests when src prop is passed as ${url}`, async ({
```

2023-10-11 08:17 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +      await mount(<ProfileComponent initials={passInitials} name={name} />);
**suggestion** in this specific scenario I think we want to be testing without initials being passed, so remove `initials={passInitials}`

2023-10-11 08:17 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +      await mount(<ProfileComponent email={email} src={testImage} />);
**suggestion** we don't need to pass the src prop here, so remove `src={testImage}`

2023-10-11 08:17 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +      await mount(<ProfileComponent name={name} src={testImage} />);
**suggestion** we don't need to pass the src prop here, so remove `src={testImage}`

2023-10-11 08:20 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +  test(`should render profile component with className`, async ({
```suggestion
  test(`should render with className`, async ({
```

2023-10-16 08:56 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +      await mount(<ProfileComponent initials={passInitials} name={name} />);
I can see this hasn't been addressed, is this because the test is failing if we don't specifically pass the initials prop?

2023-10-16 08:56 UTC, tomdavies73 commented on src/components/profile/profile.pw.tsx
> +    test(`should render with correct width and height, when initials prop is passed as ${passInitials}`, async ({
**issue**: this still needs to be addressed, imo this test is redundant as we're only testing one size (Medium) when the initials prop is passed. Instead we should be replicating the test above if we decide to keep it in. 

Also a new test needs to be made which achieves what the original cypress test was supposed to be doing, which is passing a name, no initials and ensuring initials are generated anyways due to our built in functionality `function acronymize(str?: string) {
  if (!str) return "";
  const matches = str.match(/\b\w/g);
  if (!matches) return "";
  return matches.join("");
}`

2023-10-17 08:50 UTC, stephenogorman commented on src/components/profile/profile.pw.tsx
> +      await expect(initialPreview(page)).toHaveCSS("width", "38px");
Has this been applied?

2023-10-17 11:09 UTC, stephenogorman approved these changes

2023-10-17 14:48 UTC, merged

2023-10-17 15:52 UTC, carbonci commented
:tada: This PR is included in version 121.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/121.2.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v121.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: