test(pod): playwright refactor
Sage/carbon pull request #6430
Opened 2023-11-16 09:49 UTC by ZhuoyuJin

### Proposed behaviour

Refactor Pod tests from Cypress to Playwright

### Current behaviour

Tests are currently Cypress

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

N/A

### Testing instructions

### Testing instructions
- [ ] Run Pod tests in Playwright Test Runner to check if the `pod.pw.tsx` file passed
- [ ] Run all other tests in Playwright Test Runner to check none of the other `*.pw.tsx` files have regressed

2023-11-16 21:47 UTC, divyajindel requested changes

2023-11-16 21:47 UTC, divyajindel commented on src/components/pod/pod.pw.tsx
> +test.describe("Prop tests for Pod", () => {
```suggestion
test.describe("prop checks for Pod component", () => {
```

2023-11-16 21:47 UTC, divyajindel commented on src/components/pod/pod.pw.tsx
> +      test(`should render with ${boolVal} as border and ${px} as border value`, async ({
```suggestion
      test(`should render with border value as ${borderValue} when border prop is ${boolVal}`, async ({
```

2023-11-16 21:47 UTC, divyajindel commented on src/components/pod/pod.pw.tsx
> +    ([boolVal, px, style, color]) => {
```suggestion
    ([boolVal, borderValue, style, color]) => {
```

2023-11-16 21:47 UTC, divyajindel commented on src/components/pod/pod.pw.tsx
> +        await checkCSSOutline(elem, px, "border", style, color);
```suggestion
        await checkCSSOutline(elem, borderValue, "border", style, color);
```

2023-11-16 21:47 UTC, divyajindel commented on src/components/pod/pod.pw.tsx
> +      test(`should render with ${size} as size and ${expectedHeight} as height and ${expectedWidth} as width`, async ({
```suggestion
      test(`should render with ${size} size when height is ${expectedHeight} and width is ${expectedWidth}`, async ({
```

2023-11-16 21:53 UTC, divyajindel commented on src/components/pod/pod.pw.tsx
> +  });
I'm not sure if variant has been tested here properly. All of the tests looks similar to me so could you please have a look.

2023-11-16 21:53 UTC, divyajindel commented on src/components/pod/pod.pw.tsx
> +  });
I'm not sure if variant has been tested here properly. All of the tests looks similar to me so could you please have a look.

2023-11-17 13:17 UTC, Parsium commented on src/components/pod/pod.pw.tsx
> +  variantTypes1.forEach((variantType) => {
**comment(non-blocking)**: as `variantTypes1` and `variantTypes2` are both only used once, we could alternatively replace these variables with directing passing an array to the `forEach`:

```tsx
(["h1", "h2", "h3", "h4", "h5"] as const).forEach((variantType) => {
  // tests...
})
```

2023-11-21 10:26 UTC, Parsium approved these changes

2023-11-22 11:05 UTC, divyajindel approved these changes

2023-11-23 11:31 UTC, merged

2023-11-23 11:58 UTC, carbonci commented
:tada: This PR is included in version 123.10.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/123.10.2)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v123.10.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: