test(search): convert tests from cypress to playwright - FE-6152
Sage/carbon pull request #6458
Opened 2023-11-28 09:45 UTC by DipperTheDan

### Proposed behaviour

Tests should use Playwright

### Current behaviour

Tests use Cypress

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

N/A

### Testing instructions

N/A

2023-11-28 14:57 UTC, edleeks87 reviewed
Looks like we still have the [cypress locator files](https://github.com/Sage/carbon/tree/950b282155cc570565e2d0cfb59399262edd5c61/cypress/locators/search) to remove

2023-11-28 15:31 UTC, DipperTheDan commented on src/components/search/search.pw.tsx
> +  test.skip("should render Search component", () => {
Yeah it still fails accessibility checks. I'll use `Box` as we need to provide a background colour for this test.

2023-11-29 16:18 UTC, edleeks87 approved these changes

2023-11-30 11:22 UTC, stephenogorman requested changes

2023-11-30 11:22 UTC, stephenogorman commented on src/components/search/search.pw.tsx
> +test.describe("when focused", () => {
```suggestion
test.describe("When focused", () => {

2023-11-30 11:22 UTC, stephenogorman commented on src/components/search/search.pw.tsx
> +test.describe("check props for Search component", () => {
```suggestion
test.describe("Prop tests for Search component", () => {

2023-11-30 11:22 UTC, stephenogorman commented on src/components/search/search.pw.tsx
> +test.describe("check functionality for Search component", () => {
```suggestion
test.describe("Functionality tests for Search component", () => {

2023-11-30 11:22 UTC, stephenogorman commented on src/components/search/search.pw.tsx
> +test.describe("accessibility tests for Search", () => {
```suggestion
test.describe("Accessibility tests for Search", () => {

2023-12-01 10:45 UTC, stephenogorman approved these changes

2023-12-01 10:45 UTC, edleeks87 approved these changes

2023-12-01 12:17 UTC, merged

2023-12-01 14:15 UTC, carbonci commented
:tada: This PR is included in version 124.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-react/v/124.0.0)
- [GitHub release](https://github.com/Sage/carbon/releases/tag/v124.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: