fix(submenu): ensure submenu has expected width in Safari
Sage/carbon pull request #7131
Opened 2024-12-16 16:12 UTC by nuria1110

fix #7112

### Proposed behaviour

MenuItem within a submenu extends to the expected width. 

### Current behaviour

MenuItem within a submenu with overflow gets cut off in Safari. 

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

### Testing instructions

2024-12-17 09:42 UTC, edleeks87 requested changes
I'm not sure we can go with this fix as if they haven't set the props on the MenuItem to adjust the width style properties (likely they won't) it looks like below

![image](https://github.com/user-attachments/assets/eea7a64d-9859-4fc0-9d9f-759ab85dbd85)

It does the same in both chrome and safari unfortunately

2024-12-17 16:53 UTC, edleeks87 approved these changes

2024-12-18 10:29 UTC, Parsium approved these changes

2024-12-19 08:01 UTC, dariusbercea-sage approved these changes

2024-12-19 12:14 UTC, merged